### ISSUE TITLE
UnreadCardCountForCategories not returning count on app start

### ISSUE THREAD

**Issue by Bucimis** [Appboy/appboy-ios-sdk#107] opened 2017-04-26 15:48 UTC
Ported from https://github.com/Appboy/appboy-xamarin-bindings/issues/1#issuecomment-297441780

Original comment by @machive:

```
I'm having this problem right now with the call to unreadCardCountForCategories aways returning 0. I am running the 2.27 version of the SDK. I also call the requestFeedRefresh before asking for the unread count but it still returns 0. I know new cards are being added to the feed because I see them when I bring up my feed view controller.

My problem is happening with Xcode and the Appboy SDK, not with Xamarin but it certainly seems like the same problem.

Any ideas?
```

**Comment by Wenzhi** [comment] 2017-05-08 17:59
Hey @machive:

Could you answer following questions:
- Have you checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue?

- What is your environment?

Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

- Can you pass your integration code for the News Feed, especially if you have any customization? 
We couldn't reproduce the issue on our sample app, so if you can pass your code snippet of how you integrate and customize News Feed, it will help us to reproduce and investigate the issue.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-08 18:06
Hello, 

  Answers are below. We started seeing some unread card counts coming through last week but are not sure the issue has been completely solved. 

  Best, 

  Larry 


> On May 8, 2017, at 1:59 PM, Wenzhi <notifications@github.com> wrote:
> 
> Hey @machive <https://github.com/machive>:
> 
> Could you answer following questions:
> 
> Have you checked Appboy's documentation <https://www.appboy.com/documentation/iOS/> and am still experiencing the issue?
> 
> What is your environment?
> 
> Info	Value
> Platform Name	e.g. ios / tvos			iOS
> Platform Version	e.g. 8.0				iOS 9+
> SDK Version	e.g. 3.7.6				2.27
> Integration Method	e.g. carthage / cocoapods / manually CocoaPods
> Xcode Version	e.g. Xcode 7.3			8.2.1
> Repro rate	e.g. all the time (100%) / sometimes x% / only once - Always before last week, not sure now 
> Can you pass your integration code for the News Feed, especially if you have any customization?

No customization on the Newsfeed. I'm using the stock view controller.

> We couldn't reproduce the issue on our sample app, so if you can pass your code snippet of how you integrate and customize News Feed, it will help us to reproduce and investigate the issue.

I am using the standard Newsfeed view controller and calling this code at various points in my app to fetch the number of unread cards…

    NSInteger unreadCardCount =  [[Appboy sharedInstance].feedController unreadCardCountForCategories:ABKCardCategoryAll];
    [[UIApplication sharedApplication] setApplicationIconBadgeNumber: unreadCardCount];
    [[UIApplication sharedApplication] cancelAllLocalNotifications];


Let me know if you have any other questions. 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-08 18:16
Hey Larry,

May I ask where/when you call the `unreadCardCountForCategories:`? If you call it before the SDK finishes fetching the news feed cards, the unread card count can be wrong. I'll recommend listening to [`ABKFeedUpdatedNotification`](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/ABKFeedController.h#L33). You can see the sample code in the link to the documentation.
Please let us know if that solves your issue.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-08 19:34
Hello Wenzhi, 

  I call the unreadCardCountForCategories: method in 

didFinishLaunchingWithOptions: as well as in one of my other view controllers that displays the news feed. 

  So, I changed the call to wait for the notification and it seems better but the count gets reset to 0 even though the card has never been shown in a view controller. That means that the second time I bring up the app, the card count goes to 0. 

  Is there anything I can do to prevent that behavior? 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-08 21:19
Hey Larry,

Could you create a sample app to reproduce the issue and share it through Github, or send it over to wenzhi@appboy.com? I tested it on our sample app, and the unread card count doesn't get reset after I hard close the app, or background and foreground the app.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-08 22:02
Hello Wenzhi: 

  If I get a chance, I could try to create a sample app, but could I ask a few questions first? 

  Does a call to: 

[[Appboy sharedInstance] requestFeedRefresh];

reset the count? 

I'm embedding the ABKFeedViewController in a UIView in a storyboard and this gets set up as an embed segue on the view. 

Anyway, I assumed that the card actually showing in the view would be the only thing that would reset the count but it appears to be happening for some other reason. 

Which actions reset the count? Any ideas? 

Best,

Larry

**Comment by Wenzhi** [comment] 2017-05-08 22:11
Hey Larry,

`[[Appboy sharedInstance] requestFeedRefresh];` can reset the count when:
- The user is changed, and the new user has a different unread card count
- The user has viewed the cards somewhere else(e.g. on another device), and the data is synced to the Appboy server.

Also, when a new session starts, the SDK will request the Feeds for the user as well, so when you open a new session, the above cases are also true, even when you don't call `requestFeedRefresh`.

Other than that, viewing ABKFeedViewController should be the only place that updates the unread card count.

Please let me know if you have more questions or my answers aren't clear.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-08 22:15
Hello Wenzhi, 

  Thanks for the quick reply. So, when should I call requestFeedRefresh? If I use the ABKFeedViewController, do I need to call requestFeedRefresh at all? 

  Best, 

  Larry

**Comment by machive** [comment] 2017-05-09 15:14
Hello Wenzhi, 

  I’m still a little confused about how the call to unreadCardCountForCategories: works, or, when the count is updated. 

  If I send out a newsfeed card and see the count in one of my icons, but never bring up the news feed, the count is still set to zero when I set the badge icon when the app is put in the background. 

  It seems to be that the count should stay stable with multiple calls to unreadCardCountForCategories if the newsfeed has not been displayed. 

  Thoughts? 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-09 16:16
Hey Larry,

#### Regarding calling `requestFeedRefresh`:
Usually, we don't recommend calling `requestFeedRefresh` too often to avoid unnecessary data usage for end users. However, it depends on your use case. 

In general, if you only use the `ABKFeedViewController`, you don't need to call `requestFeedRefresh` separately. But from the code you provided, you are setting the application badge number based on the unread card count, then it will depend on when you want to update the badge number, and how frequently you change news feed cards. 

#### Regarding `unreadCardCountForCategories`:
The `unreadCardCountForCategories` is tied to each user, so if the user saw all the cards on another device, the `unreadCardCountForCategories` can change even if the News Feed isn't opened on this device. There are also other scenarios(e.g. the ABKFeedViewController is loaded without being on the screen, etc) which can change `unreadCardCountForCategories`. If you can provide a sample app with the issue, it would help us investigate.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-09 16:41
Hello Wenzhi, 

  Thanks for the detailed response. Some comments below:

> On May 9, 2017, at 12:16 PM, Wenzhi <notifications@github.com> wrote:
> 
> Hey Larry,
> 
> Regarding calling requestFeedRefresh:
> 
> Usually, we don't recommend calling requestFeedRefresh too often to avoid unnecessary data usage for end users. However, it depends on your use case.
> 
> In general, if you only use the ABKFeedViewController, you don't need to call requestFeedRefresh separately. But from the code you provided, you are setting the application badge number based on the unread card count, then it will depend on when you want to update the badge number, and how frequently you change news feed cards.
> 

Thanks for that information, so, I shouldn’t have to call requestFeedRefresh if I’m only using the ABKFeedViewController, and that is all that I’m using. I’ll try it that way. 

I upgrade the badge count when the app goes into the background. 

I’m hoping the badge count gets updated automatically when the app is not active but I think that requires a setting on the AppBoy console. I don’t think I’ve seen that work yet. 


> Regarding unreadCardCountForCategories:
> 
> The unreadCardCountForCategories is tied to each user, so if the user saw all the cards on another device, the unreadCardCountForCategories can change even if the News Feed isn't opened on this device. There are also other scenarios(e.g. the ABKFeedViewController is loaded without being on the screen, etc) which can change unreadCardCountForCategories. If you can provide a sample app with the issue, it would help us investigate.
> 
> 

  To be honest, I don’t think I need to provide a sample app. The problem, in my opinion, is that you’re resetting the card count when the ABKFeedViewController is loaded even though the user has not seen any cards. I don’t feel this is correct. 

  Why aren’t you using:

- (NSArray *)indexPathsForVisibleRows

 in Objective C, or 

public var indexPathsForVisibleRows: [NSIndexPath]? { get }
 in Swift, to determine exactly which cards have been displayed to the user?

  There are a lot of scenarios where you’ll mark the cards as all being read when the user has not seen some or all of the cards. 

  I’m the only user logged in to the app looking at the card counts so it isn’t that I’m seeing the cards on another device. 

  I can try to restructure my app to not load the ABKFeedViewController view until needed but I don’t think that will be enough to get it to work correctly.

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-09 17:07
Hey Larry,

Thank you for the suggestion. When I said "the `ABKFeedViewController` is loaded changes unread card count", I meant that when the view controller's `viewDidAppear:` is called. Sorry for the miscommunication. 

> I’m hoping the badge count gets updated automatically when the app is not active but I think that requires a setting on the AppBoy console.

I think you can do it by sending a background enabled push notification to wake up the app and update the badge number. Otherwise, Appboy SDK will not, and should not wake up the host apps in the background automatically.

Please let us know if restructuring the app solves the issue.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-09 17:34
Hello Wenzhi,

  Thanks for the prompt reply. Comments below. 


> On May 9, 2017, at 1:07 PM, Wenzhi <notifications@github.com> wrote:
> 
> Hey Larry,
> 
> Thank you for the suggestion. When I said "the ABKFeedViewController is loaded changes unread card count", I meant that when the view controller's viewDidAppear: is called. Sorry for the miscommunication.
> 
> 


  Well, I think it is more complicated than that and that there are other things going on. ;-) As part of the app coming up, and the actions of the segue and the layout views, viewDidAppear gets called but the view is never made visible. 

  But, here is what I have seen:

1) App comes up, viewDidAppear is called in controller that has the feed view embedded in it. 

2) Call is made after that to the unreadCard count method and it returns 1. This is correct, there is one unread card. 

3) I background the app without bringing up the feed controller, viewDidAppear does not get called, I have breakpoints set there. The card count is decremented to 0. I believe this is incorrect. 

I don’t know why the card count should go to zero if the app is backgrounded and the user has never seen the feed view. 

> I’m hoping the badge count gets updated automatically when the app is not active but I think that requires a setting on the AppBoy console.
> 
> I think you can do it by sending a background enabled push notification to wake up the app and update the badge number. Otherwise, Appboy SDK will not, and should not wake up the host apps in the background automatically.
> 
> Please let us know if restructuring the app solves the issue.
> 
 I understand about the first part.

  I don’t think I’ll have time now to restructure the app as we want to push to the store soon, and, anyway, I don’t believe that would fix all of the problems. If you have, say, eight unread cards, and the user sees only the first four, I think you will still mark all of the cards as being read. I won’t be able to fix that problem through any restructuring. 

Best,

Larry

**Comment by Wenzhi** [comment] 2017-05-09 17:49
Hey Larry,

I agree with you that the unread card count shouldn't be reset to 0 at step 3). I also agree that when there are 8 cards, and the user only views 4 cards, the unread card count should be 4. 

However, the issue you are reporting cannot be reproduced on any of our sample apps, and you are the only one who've seen this issue in our iOS SDK. A sample app with the issue from you will allow us to continue our investigation. It will also help us to investigate whether it's an integration issue or an SDK bug.

It will be really appreciated if you can help us reproduce this issue on our end by sending us a sample app with this issue.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-09 21:50
Hello Wenzhi, 

  Well, it’s tough, I don’t have the time to build a sample app. 

  Could you tell me which version of the SDK you’re using? I’m using: 

pod 'Appboy-iOS-SDK', '~>2.27’

  Do you think there is any chance the behavior is fixed in newer version of the SDK? I’m still stuck on Xcode 8.2.1 because of its support for Swift 2.3, something that is not supported in Xcode 8.3

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-10 15:15
Hey Larry,

The `'~>2.27’` means "install the latest version available from 2.27.0". Could you check your Podfile.lock and see what's the actual version you are using? I tested the feature with the latest version 2.29.0.

Though, I don't think we have any change for News Feed in the last couple releases. May I ask which [News Feed context](https://www.appboy.com/documentation/iOS/#news-feed-view-controller-integration-options) you are using in your storyboard?

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-10 15:16
Hello Wenzhi, 

  So, I upgraded from 2.27 to 2.29 and the counts certainly got better but I believe you still have a bug with your use of the viewDidAppear method. I don’t think you can depend on the viewDidAppear method to decrement the card count because viewDidAppear can be called in many cases when the view will never be displayed. That’s what is happening with my app. 

I think this description is similar to what is going on in my case. 

  “By the way - there was a very nice talk by Greg Parker (IIRC) at WWDC 2014 about Transitions and Animations. When you are starting a Transition by draging your finger over the screen of an iDevice and releasing the screen the animation takes over. But there are szenarios where the viewDidAppear method gets called but the view is never going to appear on screen because the transition is in charge of the szenario and not the animation...
 
He has a good laugh about his collegues teasing him about the method name that perhaps should better be viewMayAppear or viewIsVeryLikelyToAppearSomeTimeLater…"

from:

https://forums.developer.apple.com/thread/15441 <https://forums.developer.apple.com/thread/15441>


Best,

Larry

**Comment by machive** [comment] 2017-05-10 15:19
Hello Wenzhi, 

  I just sent you a note….

  I have definitely noticed changes in the card counts when moving from 2.27 to 2.29….
Now the lock file says...
 - Appboy-iOS-SDK (2.29.0):
    - Appboy-iOS-SDK/UI (= 2.29.0)
  - Appboy-iOS-SDK/UI (2.29.0):

another comment below...

> On May 10, 2017, at 11:15 AM, Wenzhi <notifications@github.com> wrote:
> 
> Hey Larry,
> 
> The '~>2.27’ means "install the latest version available from 2.27.0". Could you check your Podfile.lock and see what's the actual version you are using? I tested the feature with the latest version 2.29.0.
> 
> Though, I don't think we have any change for News Feed in the last couple releases. May I ask which News Feed context <https://www.appboy.com/documentation/iOS/#news-feed-view-controller-integration-options> you are using in your storyboard?
> 
> 

  I am using the generic context…

ABKFeedViewControllerGenericContext


Is that ok?

Best, 

Larry

**Comment by machive** [comment] 2017-05-10 15:22
(Forgot reply all)

Hello Wenzhi, 

  I just sent you a note….

  I have definitely noticed changes in the card counts when moving from 2.27 to 2.29….
Now the lock file says...
 - Appboy-iOS-SDK (2.29.0):
    - Appboy-iOS-SDK/UI (= 2.29.0)
  - Appboy-iOS-SDK/UI (2.29.0):

another comment below...

> On May 10, 2017, at 11:15 AM, Wenzhi <notifications@github.com <mailto:notifications@github.com>> wrote:
> 
> Hey Larry,
> 
> The '~>2.27’ means "install the latest version available from 2.27.0". Could you check your Podfile.lock and see what's the actual version you are using? I tested the feature with the latest version 2.29.0.
> 
> Though, I don't think we have any change for News Feed in the last couple releases. May I ask which News Feed context <https://www.appboy.com/documentation/iOS/#news-feed-view-controller-integration-options> you are using in your storyboard?
> 
> 

  I am using the generic context…

ABKFeedViewControllerGenericContext


Is that ok?

Best, 

Larry

**Comment by machive** [comment] 2017-05-10 15:45
Hello Wenzhi, 

  Unfortunately, I can no longer build my app for distribution from Xcode 8.2.1…I get this error: 

Invalid bitcode version (Producer: '802.0.38.0_0' Reader: '800.0.42.1_0’)

which I believe traces back to upgrading to Appboy 2.29. 

Sigh. 

Does the 2.29 version of Appboy require Xcode 8.3? If so, I’m in trouble, as I have a ton of work to do to upgrade to Swift 3 and no time to do it right now…

Do you know of any way around this error?

Best,

Larry

**Comment by Wenzhi** [comment] 2017-05-10 15:50
Hey Larry,

Yes, SDK version 2.29.0 is for Xcode 8.3 and above. You can downgrade the SDK back to version 2.28.0. 

Also, as you don't have time to create a sample app, maybe we can do a screen share so I can help looking at the issue directly?

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-10 15:50
The answer is to turn off the “Enable Bitcode” build option in the Appboy-iOS-SDK target…..in build settings…BUT

ld: '/Users/lawrencekellogg/Library/Developer/Xcode/DerivedData/trove-dnymeokfgqediiapcesnwqiwbtux/Build/Intermediates/ArchiveIntermediates/trove copy/BuildProductsPath/Release-iphoneos/Appboy-iOS-SDK/Appboy_iOS_SDK.framework/Appboy_iOS_SDK' does not contain bitcode. You must rebuild it with bitcode enabled (Xcode setting ENABLE_BITCODE), obtain an updated library from the vendor, or disable bitcode for this target. for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)


ugh…

Your library will not build under Xcode 8.2.1 with bitcode enabled so I think I’m stuck….



Larry

**Comment by Wenzhi** [comment] 2017-05-10 16:09
Hey Larry,

Please see my last note and let us know how you want us to approach you. My email is wenzhi@appboy.com and I'm happy to set up a call with you.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-10 16:21
Hello Wenzhi, 

  Well, at this point, I think I would recommend that I move my app up to Xcode 8.3, something that I have been meaning to do anyway. 

  I think you need to look at the use of viewDidAppear on your side and figure out if there is some other way you can handle decrementing the card count that does not rely on that method. 

  My feed view controller is an embed segue in a storyboard and works fine, except for the card count, so I really don’t think I’ll try to restructure it at this time. 

  I’m not sure a phone call is needed, to be honest, although I'm certainly open to one. Let me discuss the situation with my manager first. 

  I certainly appreciate all of your help! 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-05-24 17:52
Hey Larry,

Is this still an issue for you? Can I close this issue? Please let us know if you still see the same issue in the latest version of the SDK.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-05-24 18:01
Hello Wenzhi, 

  Thanks for the followup. I completed the migration to Swift 3 and Xcode 8.3.2 just a few days ago and still need to get back to testing the unread counts. 

  I’ll let you know when I’ve done that! 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-06-17 06:24
Hey @machive, 

How's the migration going? Did you get a chance to test it out? Please let us know. :)

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-06-20 13:29
Hello Wenzhi, 

 I did finish the migration but I’ve moved away from the Newsfeed for a while to work on other features. I’ll let you know when I get back to it, it could be a while. 

  Best, 

  Larry

**Comment by Wenzhi** [comment] 2017-07-14 22:41
Hey @machive, 

Just want to follow up and see if you still see the issue. If you haven't got a chance to test it yet, do you mind I close this issue for now? You can always re-open it when you see the same problem again.

Thanks,
Wenzhi

**Comment by machive** [comment] 2017-07-15 09:08
Hello Wenzhi,

 That's fine, I'm not sure when I'll get back to the newsfeed. I'll re-open this ticket if I see the same problem again.

  Best,

 Larry

**Comment by Wenzhi** [comment] 2017-07-17 14:26
Thank you! :D

**Closed by Wenzhi** 2017-07-17 14:26 UTC
