### ISSUE TITLE
`unreadCardCount` method does return 0 if not presenting the view

### ISSUE THREAD

**Issue by leonardo-ferreira07** [Appboy/appboy-ios-sdk#153] opened 2018-06-15 13:45 UTC
Hello, 

How are you?

I'm using this Braze SDK call: `Appboy.sharedInstance()?.feedController.unreadCardCount(forCategories: .all)` to get the unread cards count for the current user. The problem is that if I call the method above *before* presenting the `NewsFeedViewController`, this returns me 0, always. 
After the `NewsFeedViewController` is presented, then the number is updated to 1 or the number of unread cards, as expected.

We expect this one to work and return the real value of unread cards, even without presenting the `NewsFeedViewController`, as we wanna update the badge for news feed, even if the user did not open the news feed view yet. I did not have the chance to check the library code, but it seems that this number is somehow updated only when the view is presented, like in `viewWillAppear` view controller method.

Thank you very much. 😄

**Comment by chshapiro** [comment] 2018-06-18 18:46
Hey @leonardo-ferreira07,

Can you try calling [`requestFeedRefresh`](https://github.com/Appboy/appboy-ios-sdk/blob/master/AppboyKit/headers/AppboyKitLibrary/Appboy.h#L508) and see if you get the right amount of cards after that?

Thanks,
Chava

**Comment by leonardo-ferreira07** [comment] 2018-06-19 15:42
Hey @chshapiro,

I've tried it as well, unfortunately it didn't work. 
You can test as I described, it only really updates after the view is shown in the screen. Calling `requestFeedRefresh` does not show up the right amount of cards.

Thank you.

**Comment by chshapiro** [comment] 2018-06-19 15:55
Hey @leonardo-ferreira07,

Unfortunately we cannot reproduce this issue in our test app. It's possible that you are calling this method before the feed is fully updated.

Can you try following the directions in this documentation to add an observer that will make sure the method is only called once the feed is fully refreshed?
https://www.braze.com/documentation/iOS/#linking-handling-customization

Thanks,
Chava

**Comment by leonardo-ferreira07** [comment] 2018-06-19 19:11
Hello @chshapiro,

Ok, but I could not find the observer protocol in this link that you've added, this link is related to deeplinking inside the app.

Thank you.

**Comment by chshapiro** [comment] 2018-07-02 15:19
@leonardo-ferreira07, closing for now. Please reopen the issue if you have any further questions. Thanks!

**Closed by chshapiro** 2018-07-02 15:19 UTC

**Comment by leonardo-ferreira07** [comment] 2018-07-02 16:56
Awesome @chshapiro, thank you very much! 
I did not have the time to test it out, but I'll do and reopen if need anything.

Thank you!

**Comment by imbenham** [comment] 2018-07-05 19:29
@leonardo-ferreira07 Did you ever get this to work?  I am having the exact same problem in version 3.6.0.  I call to refresh the feed and handle the successful update, but the count is always 0, even before the ABKNewsFeedTableViewController subclass is instantiated.

**Comment by imbenham** [comment] 2018-07-10 14:07
@leonardo-ferreira07 I see.  I think it will work once you try that.  I realized my issue stemmed from calling unreadCardCount(forCategories: .all) on an instance of ABKFeedController I'd initialized rather than on the instance exposed through the Appboy.sharedInstance()?.feedController property.  unreadCardCount is an instance method but it will always return 0 if it's called on any instance of ABKFeedController other than the one belonging to the Appboy singleton.  It's kind of an unusual pattern for an API, but it does work.
