### ISSUE TITLE
Most recent event fired is never flushed from Appboy cache

### ISSUE THREAD

**Issue by manderson-productions** [Appboy/appboy-ios-sdk#64] opened 2016-04-26 17:30 UTC
Hi!

I noticed an issue whereby the most recent event that is fired using `logCustomEvent:EVENT_NAME` appears to stay in the local Appboy cache, and is then incremented in the Appboy dashboard indefinitely whenever a new app session begins (i.e. remove instance from memory and rebuild/reopen). The following test case is fully reproducible in a test app that I created with 2 analytic events:

1. Create an app via the AppBoy dashboard on the web.
2. Use the iOS sdk installation instructions using either Swift or Objective-C as your preferred language.
3. Once the sdk is integrated and you add the `Appboy.startWithApiKey("YOUR_API_KEY", inApplication: application, withLaunchOptions: launchOptions)` call in the app delegate, go ahead and add two UIButtons to the main view controller. The first button should fire the event "Analytic ONE" and the second button should fire the event "Analytic TWO".
4. Build and Run the application in XCode.
5. Tap the "Analytic ONE" button so that `Appboy.sharedInstance()?.logCustomEvent("Analytic ONE")` is called.
6. You should see the new event registered on Appboy dashboard and the count should equal 1.
7. Stop running the app in XCode.
8. Build and run the app again in XCode WITHOUT firing any events (only the `startWithApiKey:` method will be called from the app delegate).

Expected: The "Analytic ONE" event count in the Appboy console should remain at 1.

Actual: The "Analytic ONE" event will increment to 2 (you may need to refresh a couple of times and/or wait a few seconds for the phantom count increment to occur). You can continue stopping and rebuilding the app within XCode without firing any more events and the count will continue to increment indefinitely. Additionally, you can build and run the app again tomorrow, which will cause the event to fire for YESTERDAY's stats...

Also note that if you delete the app from the home screen, clean XCode, and rebuild, the count will stop incrementing- which leads me to believe there is a bug that prevents the most recent logged event to be flushed from the local device cache.

This bug only affects the most recent event. If you press the "Analytic TWO button", which causes the `Appboy.sharedInstance()?.logCustomEvent("Analytic TWO")` method to be fired, then stop and rebuild the app in xcode, the "Analytic TWO" event will now continue to increment while the Analytic ONE event stays stationary.

This could have a really substantial impact on our analytics tracking with ~200k users / month. Let me know if there is something I missed wrt expected behavior for your analytics tracking events and/or when you believe this issue will be fixed. Thanks!

Using Appboy-iOS-SDK (2.19.2) / SDWebImage (3.7.5)
Using XCode Version 7.3 (7D175)
Using iPhone 6S, 9.3.1 or any iOS Simulator device

**Comment by briancaw** [comment] 2016-04-26 17:57
Hi @manderson-productions 

Thanks very much for reporting this.  We've been unable to reproduce this so far, but we're actively investigating and will continue to do so.  

Would it be possible for you to share that sample app with us?  Also, if you could reach out to me at brian@appboy.com we'd like to inquire more about your setup/environment and we can avoid publishing any sensitive info if we chat over email.

Thanks,
Brian

**Comment by manderson-productions** [comment] 2016-04-26 18:13
Great, thanks Brian. I just sent you an email.

Mark Anderson
Software Engineer

**Comment by billmag** [comment] 2016-04-26 20:26
Hey Mark-

Thanks for reporting this. We've identified the issue as triggering with a combination of a race condition related to the flush which occurs and a force quit (or crash) which happens when you hit "Stop" in XCode.

The exact situation that would need to occur is after a regular network flush happens, the app would need to crash or be force closed before anything else is recorded by the SDK (thus any of these things would keep it from happening: the user fires another event or purchase, an update is made to a user attribute, a location ping is recorded, your customer locks/sleeps their phone, or your customer closes the app in the normal fashion by hitting the home button).

As an example, in your steps to repro, if you were to hit Analytic TWO after the network flush, but before force closing the app, you will not see the issue (we confirmed this in the sample app you sent over). Similarly, if you hit the home button (command-shift-h in the simulator) at any time, you will also not see the issue.

Brian will update you soon with our plan to release an update to fix this issue. We were planning on releasing a minor version bump before the end of the week with a couple of other issues fixed, so we can bundle this in and move the schedule forward to get it out promptly.

-Bill

**Comment by briancaw** [comment] 2016-04-26 21:35
Hey @manderson-productions,

We will be releasing tonight with this update.  Please let us know if you have any further comments/questions; we'll ping again when we've released.

Thanks,
Brian

**Comment by manderson-productions** [comment] 2016-04-26 23:07
@briancaw Great thanks for the speedy fix! Will do some testing later this week once we update and let you know how everything is going.

**Comment by Wenzhi** [comment] 2016-04-27 01:27
Hi @manderson-productions,

The new SDK 2.19.3 with the fix for this issue is released. I'm going to close the issue for now. Please feel free to re-open this issue if you still see it happen in the new SDK.

Thanks,
Wenzhi

**Closed by Wenzhi** 2016-04-27 01:27 UTC

**Comment by manderson-productions** [comment] 2016-04-27 17:26
@Wenzhi We tested the updated sdk and so far everything is looking good. Thanks for the fix!

**Comment by billmag** [comment] 2016-04-27 17:31
Awesome, thanks for the follow up (and finding the issue in the first place)!
