### ISSUE TITLE
Include SDK without dependencies

### ISSUE THREAD

**Issue by keith** [Appboy/appboy-ios-sdk#46] opened 2016-02-04 23:04 UTC
We noticed that including AppBoy also pulls in `SDWebImage`:

(from our Podfile.lock)

```
  - Appboy-iOS-SDK (2.18.1):
    - SDWebImage (~> 3.7.0)
```

We were hoping you might provide a way to not include the portion of appboy that requires this (possibly with [subspecs](https://guides.cocoapods.org/syntax/podspec.html#subspec)) for those of us that don't use any of the UI related components.

Does this seem reasonable?

Thanks!

**Comment by Wenzhi** [comment] 2016-02-04 23:57
Hi Keith,

It makes total sense not to include SDWebImage if you don't use or plan on using Appboy's UI features. The reason we force it as a dependency is because the current SDK's built-in in-app message feature will crash on display without SDWebImage present. Forcing everyone to include SDWebImage allows clients who don't currently use in-app messages to try them out later without worrying about crashes on older apps.

It's on our roadmap to separate the SDK into two parts: base and UI and we are working on it as we speak. When finished, we will change the podspec to different subspecs.  It will not be finished in the near future, but we will let you know right away when it's done.

If you have any suggestions about how we can make things easier for you, or any other questions, please let us know.

Thanks,
Wenzhi

**Comment by keith** [comment] 2016-02-05 00:14
Thanks! We'll keep an eye out for the split update!

**Comment by jgrandelli** [comment] 2016-08-09 14:20
👍

**Comment by hovox** [comment] 2016-09-14 15:55
👍

**Comment by anna-sakhlyan** [comment] 2016-09-15 11:09
:+1:

**Comment by keith** [comment] 2017-02-02 20:56
Any update on the split here? Otherwise do you have any plans to upgrade SDWebImage to the newest major release?

**Comment by Wenzhi** [comment] 2017-02-02 23:06
Hey @keith,

We are planning on releasing a beta version SDK to support SDWebImage 4.0 around the end of this week or early next week. Is the timeline good for you? 

Thanks,
Wenzhi

**Comment by keith** [comment] 2017-02-02 23:13
Sounds good, thanks!

**Comment by Wenzhi** [comment] 2017-02-06 15:32
Hey @keith,

We released the 2.26.0-beta version with SDWebImage 4.0 support over the weekend. It would be great if you can try it out and let us know any issue or problem you see.

Thanks,
Wenzhi

**Comment by keith** [comment] 2017-02-06 20:08
Is the SDWebImage GIF subspec required for the UI portion of Appboy? This adds another library to our project 😞

**Comment by mlloyd** [comment] 2017-02-13 12:16
Hey @Wenzhi 

I have tried the Carthage 2.26.0-beta but the SDWebImage framework isn't working. Comparably with the version built direct from SDWebImage using Carthage.

I believe the issue is due to your zip including, the SDWebImage framework. Which is not the correct module header. It's incorrectly labelled, SDWebImage_umbrella.h Normally the include would be, #import <SDWebImage/SDWebImage.h>

For reference;
https://github.com/rs/SDWebImage/blob/4.0.0/WebImage/SDWebImage.h

Thanks, Martin

**Comment by Wenzhi** [comment] 2017-02-14 06:39
@keith,

We are currently working on creating a core suspec with no dependency to solve this specific issue. There is no timeline for the release yet but it should be in the near future. I'll inform you in this issue thread as soon as it comes out. Please stay tune :)

Thanks,
Wenzhi

**Comment by Wenzhi** [comment] 2017-02-14 06:46
Hey @mlloyd,

Thanks for reporting the issue! However, your issue doesn't relate to the original issue here. Could you create a separate issue following our issue template? It will help collecting more necessary information and stop notifying other people in this thread with an unrelated issue. 

Let's move the discussion to your issue thread! We will try to solve as fast as we can.

Thanks,
Wenzhi

**Comment by hovox** [comment] 2017-02-23 10:47
We are not using any of the ui components. Having model and UI in the separate repos would be the best option for us.

**Comment by Wenzhi** [comment] 2017-02-25 00:54
@keith/all,

We just released version 2.26.0 with two subspecs: `Core` and `UI`. The `Core` subspec has no dependencies. If you don't use Appboy UI components and want to include our library without dependencies, please change your Podfile to use `Appboy-iOS-SDK/Core`. 

If you use the `Core` subspec - in the future you may want to message users using Appboy's UI, and shipping a version without our full library can introduce friction.  For example, you may have to version-filter delivery of in-app messages and News Feed items.

Note: there are still resource files in the Core subspec. Eventually all UI items will be moved to the `UI` subspec.

For more information, please see (CHANGELOG.md)[https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md]. Please let us know if you see any issue or have any questions.

Thanks,
Wenzhi

**Comment by mlloyd** [comment] 2017-03-01 20:34
@Wenzhi 
Is it possible to use the core version with Carthage?

**Comment by Wenzhi** [comment] 2017-03-02 20:37
Hey @mlloyd,

Currently, our Core subspec does not have Carthage support because we support through a pre-built framework of our entire library.  We are actively considering strategies for more robust Carthage support but don't have any plans for an immediate change here. We will keep you posted when we have more information.

I created a separate issue [here](https://github.com/Appboy/appboy-ios-sdk/issues/103) to keep track of this Carthage support. 

Thanks,
Wenzhi

**Comment by Wenzhi** [comment] 2017-03-03 21:27
Hey All,

I'm going to close this issue as we now provide Core SDK without dependency on Cocoapods. If you see any issues or have any questions, please create an issue and let us know. :)

Thanks,
Wenzhi

**Closed by Wenzhi** 2017-03-03 21:27 UTC
