### ISSUE TITLE
#145 Re-Open : In-app message overlay is not dismissed 

### ISSUE THREAD

**Issue by jinnamohamed1** [Appboy/appboy-ios-sdk#149] opened 2018-05-23 10:10 UTC
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 9.0, 10.0, 11.0
 SDK Version             | 3.4.0
 Integration Method      | cocoa pods
 Xcode Version           |  Xcode 9.2
 Repro rate              | all the time 
 
## What did you do?

Created In-app message and launched

## What did you expect to happen?

Received In-app message on the application and pressed home button without dismissing the in-app. Expected to display the in-app which is in background

## What happened instead?

Displayed in-app grey overlay with out any in-app dialog elements. Unable to proceed anything in the app as the Overlay appeared on the top of current viewcontroller.

**Comment by chshapiro** [comment] 2018-05-23 13:14
Hey @jinnamohamed1,

Unfortunately we are not able to reproduce this issue. Can you provide more context as to how you're integrating? Are you using the InAppMessage subspec or the full SDK?

Also, are you doing any custom handling for in-app messages?

If you don't want to have this information on our public repo, please email support@braze.com and we can help you resolve this issue that way.

Thanks,
Chava

**Comment by chshapiro** [comment] 2018-06-19 15:56
@jinnamohamed1, closing for now. Please reopen the issue if you have any further questions. Thanks!

**Closed by chshapiro** 2018-06-19 15:56 UTC

**Comment by lustig-bakkt** [comment] 2021-02-12 22:14
@chshapiro I'd like to reopen this as I've got a repro here that also demonstrates that a Full Screen IAM functions as expected, therefore isolating the bug to the modal. **I've intentionally colored the overlay that silly pink to elucidate the issue.**

![2523 fix ios deeplinking iam working, braze modal broken](https://user-images.githubusercontent.com/73849817/107827872-a2729c80-6d55-11eb-8289-ccb8f6212189.gif)
