### ISSUE TITLE
registerPushToken is broken on Xcode 11

### ISSUE THREAD

**Issue by seanho** [Appboy/appboy-ios-sdk#195] opened 2019-08-14 00:47 UTC
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

`Appboy.sharedInstance()!.registerPushToken()` integration code no longer works properly on Xcode 11 due to Apple changed the default formatting for `NSData` which has been reported in Apple Developer Forums [here](https://forums.developer.apple.com/thread/119111).

In short, on Xcode 10, the formatted string looks like
`@"<44154da7 32345001 53106883 ffc1071f a59c0d24 a70871e5 aa8dbb41>"`

while on Xcode 11, it looks like
`@"{length =32, bytes = 0x44154da7 32345001 53106883 ffc1071f ... a70871e5 aa8dbb41}"`

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 13
 SDK Version             | 3.14
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 11
 Repro rate              | all the time (100%)
 
## What did you do?

Followed the documentation to integrate push notification as shown below
https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/#step-3-register-for-push-notifications

```swift
let deviceTokenString = String(format: "%@", deviceToken as CVarArg)
Appboy.sharedInstance()?.registerPushToken(deviceTokenString)
```

## What did you expect to happen?

Braze receives the `deviceTokenString ` in the expected format that can be used to send push notification to the device.

## What happened instead?

Braze is complaining about bad device token when tries to send push notification

```
Received 'BadDeviceToken' sending to 'length32bytes0x46d6fa9b90ba374832995c42dc0e93d61c43afb7545621ff'.
```

## Comment

Braze documentation does not specify what device token format they accept, e.g. base64, hex, hence it is unclear how to fix this problem without more information from Braze.

Since Apple is always returning `Data` for device token, Braze SDK should accept `Data` instead of `String` as suggested in #127 to minimize the impact on all apps using the SDK.

**Comment by hokstuff** [comment] 2019-08-16 16:55
Hi @seanho,

Thanks for reaching out about this. We are monitoring this issue and are waiting for Apple to release an update to the beta to bring the functionality back to what it was before. For now, there are workarounds for this issue to manually parse the `NSData`, but those are not supported by us.

Best,
Daniel

**Comment by mmdock** [comment] 2019-08-21 22:59
@seanho I use `deviceToken.reduce("", {$0 + String(format: "%02.2hhx", $1)})` and don't seem to be encountering this issue.  All my push tokens seem to be correct.

**Comment by seanho** [comment] 2019-08-22 04:26
@mmdock Your code is based on the assumption that Braze is accepting and storing the device token string in hex format, which is not documented anywhere in their documentation currently.

**Comment by mmdock** [comment] 2019-08-22 07:24
@seanho 🤷‍♂ 

So, `deviceToken as CVarArg`, to the best of my knowledge is equivalent to just calling `deviceToken as NSData` which would provide a hexidecimal blob.  Then when passed in to `String(format: "%@", deviceToken as CVarArg)` like that it just results in a hex string.

If you tried to just print out any NSData before it would result in hexidecimal blob being printed in console (depending on the data being represented, because this dumping behavior was changed for some data representations in Xcode 10 / swift 4.2 such as for NSInlineData and NSSwiftData: but in this case, it was still a hex dump)

Now, it defaults to calling NSData's .description which is a property list instead of doing a hex dump like before.  

Check Swift Revolution's bug ticket for Data's inability to hex dump like like NSData and offered proposal to correct that.  Which has now been updated to mention that NSData's hex dump is also broken in latest Beta releases.  

Dunno if this will get reverted and fixed, but i do know that that line of code was effectively making a hex string.  So, yeah, AppBoy effectively did document they want the hex string just by providing that code sample.  You can see in AppBoy's swift sample app's history that they used to pass in NSData into the String format function here: https://github.com/Appboy/appboy-ios-sdk/blame/7703db1f1b5f75540b5112e14353a35046e16569/HelloSwift/HelloSwift/AppDelegate.swift and updated to use `as CVarArg` after the AppDelegate changes to pass in Data instead of NSData.

Additionally, been sending this way to app boy for awhile.  The git history of my code for this is:

July 20th, 2016:
```
        let string = NSMutableString(capacity: 100)
        let pointer = (deviceToken as NSData).bytes.bindMemory(to: UInt8.self, capacity: deviceToken.count)
        for i in 0..<deviceToken.count {
            string.appendFormat("%02.2x", pointer[i])
        }
```
September 7th, 2017 it became: 
`let string = deviceToken.map { String(format: "%02.2hhx", $0) }.joined()`

Nov 12th, 2018 it became:
`let string = deviceToken.reduce("", {$0 + String(format: "%02.2hhx", $1)})`

Can verify all works well for a couple years now 👍 but i don't work for Appboy so idk, maybe i've been causing issues for my users with edge cases where they don't register or something.

**Comment by hokstuff** [comment] 2019-08-22 18:03
Hi @seanho and @mmdock,

We have recently confirmed with Apple that they are keeping their new implementation of `[NSData description]` in Xcode 11, which is causing these issues. We will release a new update that fully supports iOS 13 (including this issue) once it is out of beta. I will close this out for now - please reopen if you are still seeing issues after iOS 13 is released.

Thank you both!

**Closed by hokstuff** 2019-08-22 18:03 UTC

**Comment by shauket** [comment] 2019-09-04 03:39
This issue is fixed or not yet?

**Comment by hokstuff** [comment] 2019-09-04 18:24
Hi @shauket,

We are working on this and will release the fix with the rest of our iOS 13 support. We will reply back to this thread once that is released. In the meantime, there are workarounds to manually extract the correct device token from the `NSData` object - that should unblock you for testing until we officially support iOS 13 once it's out of beta.

Thanks!

**Comment by shauket** [comment] 2019-09-05 03:00
Can you confirm does this way is correct? deviceToken is NSData that I got
in registerpushnotification method.

  NSString* newToken = [[[NSString stringWithFormat:@"%@",deviceToken]

                         stringByTrimmingCharactersInSet:[NSCharacterSet
characterSetWithCharactersInString:@"<>"]]
stringByReplacingOccurrencesOfString:@" " withString:@""];

**Comment by hokstuff** [comment] 2019-09-05 20:01
Hi @shauket,

I won't be able to confirm if your workaround is valid, but you can test to see if push is successfully sending after your update. Here is a resource of people experiencing similar problems from Apple's forums that may be useful: https://forums.developer.apple.com/thread/117545

Best,
Daniel

**Comment by bstillitano** [comment] 2020-02-21 00:41
Is there any movement on this? It seems like there isn't an accepted solution when working with iOS 13?

**Comment by chshapiro** [comment] 2020-02-21 01:42
Hey @bstillitano,

We updated this in SDK version 3.20.2. Please update to the latest SDK version and update your code to use `[[Appboy sharedInstance] registerDeviceToken:deviceToken]` instead of `[[Appboy sharedInstance] registerPushToken:[NSString stringWithFormat:@"%@", deviceToken]];`. Please see our [Changelog](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3202) for more information.

Thanks,
Chava

**Comment by shanthakumarmv** [comment] 2020-06-13 04:38
> Hey @bstillitano,
> 
> We updated this in SDK version 3.20.2. Please update to the latest SDK version and update your code to use `[[Appboy sharedInstance] registerDeviceToken:deviceToken]` instead of `[[Appboy sharedInstance] registerPushToken:[NSString stringWithFormat:@"%@", deviceToken]];`. Please see our [Changelog](https://github.com/Appboy/appboy-ios-sdk/blob/master/CHANGELOG.md#3202) for more information.
> 
> Thanks,
> Chava

Hi Chava, am using version 3.24.1 and implemented code as you mentioned.
Still facing Push Notification Error with "BadDeviceToken"!

1. Can you help me in understanding what format/value we need to send to Appboy registration?
2. [[Appboy sharedInstance] registerDeviceToken:deviceToken] - since method expects NSData, is it fine to send same device token received from Apple? (didRegisterForRemoteNotificationsWithDeviceToken:(NSData *)deviceToken)

Your help would be much appreciated! Thanks..

**Comment by Bucimis** [comment] 2020-06-13 05:01
@shanthakumarmv yep, you can directly send the token you get from `didRegisterForRemoteNotificationsWithDeviceToken` to the SDK. If you continue to run into `BadDeviceToken` issues after that, you should ensure your environment (push credentials) are correct
