### ISSUE TITLE
Is FLAnimated Image Required

### ISSUE THREAD

**Issue by dmiluski** [Appboy/appboy-ios-sdk#164] opened 2018-10-12 16:33 UTC
* [x] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

I recently attempted to integrate with AppBoy via the instructions below:
```
binary "https://raw.githubusercontent.com/Appboy/appboy-ios-sdk/master/appboy_ios_sdk.json"
github "rs/SDWebImage"
github "Flipboard/FLAnimatedImage"
```

And I'm getting a duplicate FLAnimatedImage since SDWebImage includes FLAnimatedImage? But If I drop FLAnimatedImage from the embedded frameworks (via submodule integration), dylib fails to be found?
https://github.com/rs/SDWebImage/tree/master/SDWebImage/FLAnimatedImage

If I include both Carthage dependencies: SDWebImage + FLAnimatedImage
```
Duplicate interface definition for class 'FLAnimatedImageView'
```
If I don't include FLAnimatedImage:
```
dyld: Library not loaded: @rpath/FLAnimatedImage.framework/FLAnimatedImage
  Referenced from: /Users/<username>/Library/Developer/CoreSimulator/Devices/<ID>/data/Containers/Bundle/Application/<AppID>/<Name>.app/Frameworks/Appboy_iOS_SDK.framework/Appboy_iOS_SDK
  Reason: image not found
```

Seeing if FLAnimatedImage library was still necessary as a separate dependency for Braze?

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | e.g. ios / tvos
 Platform Version        | e.g. 8.0
 SDK Version             | e.g. 3.7.6
 Integration Method      | e.g. carthage / cocoapods / manually
 Xcode Version           | e.g. Xcode 7.3
 Repro rate              | e.g. all the time (100%) / sometimes x% / only once

**Comment by chshapiro** [comment] 2018-10-16 19:56
Hey @dmiluski,

Are you still experiencing this issue? Unfortunately, we were unable to reproduce and FLAnimatedImage is still required as a separate dependency.

Are you adding the frameworks in both the Embedded Binaries and Linked Frameworks and Libraries sections? 
<img width="667" alt="screen shot 2018-10-16 at 3 54 50 pm" src="https://user-images.githubusercontent.com/20050276/47043590-f9531180-d15b-11e8-9270-708110b08593.png">

Thanks,
Chava

**Comment by chshapiro** [comment] 2018-10-17 00:17
@dmiluski,

Are you using Swift or Objective-C? There is a known SDWebImage issue (https://github.com/rs/SDWebImage/issues/2279) that can happen when using Swift and Carthage.

Unfortunately, this is an SDWebImage issue that we can't do much about, but there is a workaround you can look at in https://github.com/Appboy/appboy-ios-sdk/issues/85.

Please let us know if you have any more questions.

Thanks,
Chava

**Comment by chshapiro** [comment] 2018-10-23 20:00
Hey @dmiluski,

Are you still running into these issues? 

Thanks,
Chava

**Comment by dmiluski** [comment] 2018-10-23 20:59
Hi @chshapiro , yeah. Since SDWebImage 5 is still in beta, going to continue using AppBoy fat binary instead of thin binary until SDWebImage 5 is a full GM release.

**Comment by chshapiro** [comment] 2018-10-23 21:02
Great! Once SdWebImage 5 is released, we are also looking into replacing our use of FLAnimatedImage with SDWebImage GIF support.

I'm going to close this issue for now. Feel free to reopen if you have further questions.

**Closed by chshapiro** 2018-10-23 21:02 UTC
