### ISSUE TITLE
Crashed at -[ABKEventLog encodeWithCoder:] (ABKEventLog.m:33) 

### ISSUE THREAD

**Issue by vevo-sterling-li** [Appboy/appboy-ios-sdk#65] opened 2016-04-26 23:54 UTC
We are at version 2.19.2, but we also saw this crash in earlier versions. Attached stack trace. 
[report (3).txt](https://github.com/Appboy/appboy-ios-sdk/files/237700/report.3.txt)
![screen shot 2016-04-26 at 4 51 13 pm](https://cloud.githubusercontent.com/assets/3066383/14837695/8217d834-0bcf-11e6-9497-e8839bfd654f.png)

**Comment by Wenzhi** [comment] 2016-04-27 00:08
HI @vevo-sterling-li,

Thanks for reporting this. Looks like a race condition between `persistDiffOfUserAgainstLastSentToServer` (which happens when you make an update to a user attribute) and modifications to the user state by our background flush. There should be mutual exclusion in there, but we appear to have an issue.

Do you have any idea of the number of occurrences of this issue in your implementation?

Thanks,
Wenzhi

**Comment by vevo-sterling-li** [comment] 2016-04-27 00:12
We got about 600+ this crash in the past 14 days.

**Comment by briancaw** [comment] 2016-04-27 00:42
Hi @vevo-sterling-li 

We're actively looking into this and will update ASAP with further information and timelines for a fix.  We have a release coming out tonight and will be investigating this with high priority as soon as that is done.  Thanks again for reporting and please let us know if you have any further comments/questions.

Thanks,
Brian

**Comment by briancaw** [comment] 2016-04-29 21:39
Hi @vevo-sterling-li 

Updating to let you know that we've identified the cause of this issue and are actively working on the fix.  The fix requires a non-trivial amount of dev work and we want to test it thoroughly, which is accounting for the delay.  We plan on releasing the fix next week.

Please let us know if you have any further comments/questions regarding this issue. 

Thanks,
Brian

**Comment by vevo-sterling-li** [comment] 2016-04-29 22:22
@briancaw Thanks for the heads up.

**Comment by Wenzhi** [comment] 2016-05-06 18:02
@vevo-sterling-li, 

The recently released SDK 2.20.0 has the fix for this issue. It would be great if you could confirm that you do not see this issue anymore after updating to this version.

Please let us know if you have any further comments/questions, and thanks again for reporting this.

Thank you,
Wenzhi

**Closed by Wenzhi** 2016-05-06 18:02 UTC

**Comment by vevo-sterling-li** [comment] 2016-05-06 18:27
@Wenzhi Thanks! We will update it in our next release.
