### ISSUE TITLE
Deep links won't open in iOS 10

### ISSUE THREAD

**Issue by justin** [Appboy/appboy-ios-sdk#72] opened 2016-06-22 19:59 UTC
It looks like whatever you all are doing to handle deep links doesn't seem to work in iOS 10. If I take a device running iOS 9 and send a push through the Appboy portal with a deep link embedded its fine. If I update the same device to 10 and repeat the deep linked push, it doesn't actually open. It just goes to the main app screen.

**Comment by briancaw** [comment] 2016-06-22 22:43
HI @justin 

Thanks for reporting - we can reproduce this and are actively investigating.  We'll respond with information regarding a fix ASAP.

Thanks,
Brian

**Comment by justin** [comment] 2016-08-08 16:20
Does 2.21.0 do anything to improve this situation?

**Comment by briancaw** [comment] 2016-08-09 11:30
Hi @justin 

2.21.0 doesn't have a fix for this in it.  We're aiming to get signal on this issue and a timeline for a fix by end of week.  Apologies for the delay here.

Thanks,
Brian

**Comment by Wenzhi** [comment] 2016-08-09 17:28
Hi @justin,

In iOS 10, there is a new delegate method `- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler` to handle notifications. To have properly functioning push handling you should call Appboy's method in the new delegate method like:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
  [[Appboy sharedInstance] registerApplication:[UIApplication sharedApplication]
                  didReceiveRemoteNotification:response.notification.request.content.userInfo
                        fetchCompletionHandler:completionHandler];
}
```

We will update our SDK/documentation with the new notification handling scheme and release it when Apple's "Golden Master" version is out. We will notify you via this issue when we’ve released the official update.  Please let us know if you have any further comments/questions, and thanks for reporting. :)

Thanks, 
Wenzhi

**Comment by justin** [comment] 2016-08-13 14:48
If the app hasn't been recompiled for iOS 10 it shouldn't try to go through this delegate method though, however. Right?

**Comment by Wenzhi** [comment] 2016-08-15 16:03
Hey @justin ,

Yes, it won't go through the new delegate method if the app is compiled with an older Xcode version, though I tested that case and didn't see the deep link issue in the iOS 10 beta 4. Are you still seeing the deep link issue on iOS 10 even if the app isn't recompiled for iOS 10? Could you give us more detail(e.g. the iOS 10 beta version) and steps to reproduce?

Thanks,
Wenzhi

**Comment by justin** [comment] 2016-08-24 16:28
Correct. This is using the latest iOS 10 beta with the latest Appboy SDK release (compiled with Xcode 7, and the iOS 9 SDK).  Any push with a deep link does not open to the deep link. 

Everything works as expected on iOS 9.

**Comment by Wenzhi** [comment] 2016-08-25 22:57
Hey @justin,

Here are the cases we tested:
- A sample app is compiled in iOS 9, and then runs in the iOS 10 environment. The deep link works for us.
- A sample app is compiled in iOS 10, with the new push delegate method implemented, and runs in the iOS 10 environment. The deep link works in this case, too.

Which case is the one that you are having issues with? Or is it none of the above? If it's one of the cases above, we can send you an working sample app, or you can share your app with us through wenzhi@appboy.com and we can help looking at it.

If none of the cases above matches your case, I apologize for the confusion on our part and would appreciate more information to reproduce the issue!

Thanks,
Wenzhi

**Comment by briancaw** [comment] 2016-09-12 01:39
Hi @justin 

Quick update here:  iOS 10 does not call `application:didReceiveRemoteNotification:fetchCompletionHandler` when the user clicks a push notification regardless of compilation target.  As a result our push tracking and deep link handling for iOS 10 won't work with our published SDK unless you implemented the `application:didReceiveRemoteNotification` and called our corresponding method from there.

 We're going to release an updated SDK in the next 48 hours that supports a `UserNotifications` delegate that should solve the problem if you can build against iOS 10 SDK.  If you can't update to build against the iOS 10 SDK, you'll have to also implement `application:didReceiveRemoteNotification` and call the corresponding Appboy method from there. 

If you could confirm that the latter solves your issue it would be much appreciated.

Thanks,
Brian

**Comment by justin** [comment] 2016-09-12 14:18
We moved to the iOS 10 SDK last week, so we can give this a whirl when it's available.

**Comment by briancaw** [comment] 2016-09-13 17:19
Hi again @justin 

We've released and updated our documentation.  If you could confirm that the new integration solves things for you it'd be much appreciated.

https://www.appboy.com/documentation/iOS/#step-3-update-application-code

Thanks,
Brian

**Comment by justin** [comment] 2016-09-16 18:52
We have this plugged in and in my personal testing it seems to work. We're fighting an xcode crasher in 8 (long story, not enough alcohol to tell right now) that is preventing us from deploying it to TestFlight right now to fully verify, however.

**Comment by benkane** [comment] 2016-09-20 22:08
Is this resolved? I feel I've updated my code completely based Appboy documentation for iOS 10, but deep linking is only working from me when the app is in the background. If I force quit an app, then try a deep linking notification, the application only opens, it doesn't perform the deep link.

**Comment by benkane** [comment] 2016-09-20 22:20
To be clear, these are my test cases:

1. Launch app, press home button, send/receive deep linking notification, app should open and perform deep link
2. Launch app, double press home button, swipe up on app to force quit, send/receive deep linking notification, app should open and perform deep link

Scenario 2 is failing for me. The app opens, but it does not perform the deep link, indicating `application:handleOpenURL:` was not called. I've tried placing deep link handling in `application:openURL:sourceApplication:annotation:` and `application:openURL:options:` as well with no luck.

**Comment by Wenzhi** [comment] 2016-09-20 22:21
@benkane,

Thanks for the report.  Can you provide us with some more information, including:

1) Is deep linking working on iOS 8/9 for you?
2) Which solution are you using? (i.e. UserNotifications or modified delegates)
3) Are push opens logged when the deep link doesn't work?

Thanks,
Wenzhi

**Comment by benkane** [comment] 2016-09-20 22:23
Hi @Wenzhi, thanks for the quick reply.

1. Deep linking does work on iOS 8/9
2. I use UserNotifications and modified delegates since I support iOS 8+ but am building for iOS 10
3. I don't know offhand, I'll get back to you on that one

**Comment by benkane** [comment] 2016-09-21 13:33
Hi again @Wenzhi,

I've checked item 3, and yes, the push opens are successfully logged when the deep link doesn't work. I made a new test campaign, sent one push to myself with a deep link, and opened it with the app fully closed. The deep link did not work; however, the open rate in the dashboard is 100%.

**Comment by benkane** [comment] 2016-09-22 15:35
I've resolved my issue. The path URL was coming through as nil in iOS >= 9.2. I was using the path to check if my app could handle the deep link. I've switched to checking the scheme + route instead. This does raise the question of whether the URL's path being nil is due to something Appboy SDK is doing, or if it's Apple making it nil. Something for you to look into if you want. I'm all set, though, thanks for the help.

**Comment by briancaw** [comment] 2016-09-22 17:50
Hi @benkane 

Thanks great to hear - thanks very much for the update.  We'll take a look at why that might have happened, but we agree that it sounds like something outside of our SDK's handling.

Closing this issue; thanks very much @justin for reporting this behavior, and please let us know if you run into any other issues.

Thanks,
Brian

**Closed by briancaw** 2016-09-22 17:50 UTC

**Comment by royherma** [comment] 2016-09-28 06:38
Hey have you guys been able to figure out what the issue is? 

I have a deep link URL that works for iOS 9, but for same app with iOS 10 it just opens safari and says "the url can't be shown".

Any ideas?

Thanks

**Comment by Sunitadaffodil** [comment] 2016-10-27 04:53
Hi all,  

I am also facing same issue , so I thought of updating AppBoy sdk in our project. For that I am following manual Integration section, so I tried to clone git repo of AppBoy. Unfortunately, I am not able clone repo, throwing error as below

"Please make sure you have the correct access rights
and the repository exists.
Permission denied (publickey)."

Could anyone suggest what needs to be done in order to clone AppBoy git repo.

**Comment by briancaw** [comment] 2016-10-28 00:31
Hi @Sunitadaffodil 

It sounds like your github authentication is not working correctly - please see http://stackoverflow.com/questions/12940626/github-error-message-permission-denied-publickey and/or check your github ssh setup.

Thanks,
Brian
