### ISSUE TITLE
Mac won't build unless iOS is built first using latest release with Cocoapods + Catalyst support

### ISSUE THREAD

**Issue by smawpaw** [Appboy/appboy-ios-sdk#284] opened 2021-03-15 21:45 UTC
* [x] I have checked [Braze's documentation](https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS / Catalyst
 Platform Version        | 13+ iOS, 14+ Catalust
 SDK Version             | 4.0.0
 Integration Method      | Cocoapods
 Xcode Version           | Xcode 12.2
 Repro rate              | 100%
 
## What did you do?

- Tried to build for Mac Catalyst without first building for iOS

## What did you expect to happen?

- Catalyst successfully builds without need to build for iOS first
- Be able to submit a Mac build to AppStore without workaround

## What happened instead?

- Get signing error `Signing for "Appboy-iOS-SDK-Appboy" requires a development team. Select a development team in the Signing and Capabilities editor.`

![image](https://user-images.githubusercontent.com/3187503/111224013-e7376080-85ab-11eb-852e-dafd6d3d3c92.png)

## Steps to reproduce

- Integrate Appboy 4.0.0 within a multi-platform project
- Select Mac as active scheme
- Try to build for mac without having built for iOS first 

## Workaround

- This may be an issue with Cocoapods. But as an FYI we were able to freely build and submit to Apple using the workaround described here: https://github.com/CocoaPods/CocoaPods/issues/8891#issuecomment-573301570
- Possible, but unverified, that other pods with Catalyst support are doing something similar
- 🙏

**Comment by hokstuff** [comment] 2021-03-16 16:46
Hi @smawpaw,

Thanks for filing this issue and linking it to the open Cocoapods issue + workaround. It looks like this is a general issue with Pods that have a setup similar to ours. In addition to the workaround linked, you can also explicitly sign each bundle under the `Pods` project to allow you to run on Mac Catalyst.

In the past, we haven't code signed our SDK because it wasn't necessary on iOS, and Cocoapods/etc would handle it automatically. However, it appears code signing is handled differently for Mac Catalyst and this issue stems from the same place [as the one here](https://github.com/Appboy/appboy-ios-sdk/issues/282). We are currently investigating in regards to signing our SDK for distribution. Let us know if you have any further thoughts.

Thank you!

**Comment by hokstuff** [comment] 2021-05-18 21:37
Updating this thread here - The Mac Catalyst signing issues in this Cocoapods thread are separate from the ones in [the related SPM thread](https://github.com/Appboy/appboy-ios-sdk/issues/282) (which has been fixed in Xcode 12.5).

Right now the best thing to do if you experience this issue is to follow the workaround provided in the original post above. This should be sufficient until Cocoapods can handle the generic root cause that this issue stems from.

Since there are no action items on our end, I am closing out this thread. If there are any concerns or if the workaround above isn't sufficient, feel free to comment on / reopen. Thank you!

**Closed by hokstuff** 2021-05-18 21:37 UTC
