### ISSUE TITLE
Exception with "news feed" from cocoapods.

### ISSUE THREAD

**Issue by semionenko** [Appboy/appboy-ios-sdk#125] opened 2017-10-09 03:30 UTC
Hi. I try to use "news feed" in my apps. I've created classic card for test with image and text. 
In app I've used cocoapods and that code:
`
ABKFeedViewControllerNavigationContext *feedVC = [[ABKFeedViewControllerNavigationContext alloc] init];
feedVC.cardWidthForiPhone = self.width * 0.95f;
self.newsAndFeedbackNavigationController = [[UINavigationController alloc] initWithRootViewController:feedVC];
[self.newsAndFeedbackNavigationController setNavigationBarHidden:YES animated:NO];
self.newsView = self.newsAndFeedbackNavigationController.view;
self.newsView.frame = CGRectMake(0.f, 45.f, self.width, self.newsView.h - 45.f);
self.newsView.hidden = NO;
[self.view addSubview:self.newsView];
`

But every time I see the exception:

*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '*** -[__NSPlaceholderDictionary initWithObjects:forKeys:count:]: attempt to insert nil object from objects[0]'
*** First throw call stack:
(
	0   CoreFoundation                      0x000000010b2ce1cb __exceptionPreprocess + 171
	1   libobjc.A.dylib                     0x000000010a54ef41 objc_exception_throw + 48
	2   CoreFoundation                      0x000000010b30de8c _CFThrowFormattedException + 194
	3   CoreFoundation                      0x000000010b1e2da1 -[__NSPlaceholderDictionary initWithObjects:forKeys:count:] + 321
	4   CoreFoundation                      0x000000010b1e2c2b +[NSDictionary dictionaryWithObjects:forKeys:count:] + 59
	5   Application                            0x0000000104150983 +[ABKThemableCardTitleLabel maxHeight] + 131
	6   Application                            0x000000010415653c -[ABKCardViewModel getTitleHeightWithWidth:forString:] + 76
	7   Application                            0x0000000104147432 -[ABKNewsCardViewModel cardHeightWithWidth:] + 290
	8   Application                            0x000000010412da2a -[ABKFeedViewController tableView:heightForRowAtIndexPath:] + 266
	9   UIKit                               0x0000000106ae8cb5 -[UITableView _dataSourceHeightForRowAtIndexPath:] + 106
	10  UIKit                               0x0000000106d93970 __66-[UISectionRowData refreshWithSection:tableView:tableViewRowData:]_block_invoke + 333
	11  UIKit                               0x0000000106d93178 -[UISectionRowData refreshWithSection:tableView:tableViewRowData:] + 3090
	12  UIKit                               0x0000000106d97499 -[UITableViewRowData numberOfRows] + 95
	13  UIKit                               0x0000000106ab4651 -[UITableView noteNumberOfRowsChanged] + 158
	14  UIKit                               0x0000000106ab3a69 -[UITableView reloadData] + 1479
	15  Application                            0x000000010412d22d -[ABKFeedViewController prepareToDisplayCards:] + 1341
	16  Application                            0x000000010412cc04 -[ABKFeedViewController feedUpdatedForDisplay:] + 324
	17  CoreFoundation                      0x000000010b26a07c __CFNOTIFICATIONCENTER_IS_CALLING_OUT_TO_AN_OBSERVER__ + 12
	18  CoreFoundation                      0x000000010b269f7a _CFXRegistrationPost + 442
	19  CoreFoundation                      0x000000010b269cc2 ___CFXNotificationPost_block_invoke + 50
	20  CoreFoundation                      0x000000010b22ba32 -[_CFXNotificationRegistrar find:object:observer:enumerator:] + 1826
	21  CoreFoundation                      0x000000010b22abac _CFXNotificationPost + 652
	22  Foundation                          0x00000001057be842 -[NSNotificationCenter postNotificationName:object:userInfo:] + 66
	23  Application                            0x00000001040a3778 -[ABKNotificationCenter postFeedUpdatedNotificationWithSuccessful:] + 248
	24  Application                            0x0000000104105d9e -[ABKService dataRequest:finishedSuccessfully:] + 750
	25  Application                            0x0000000104105937 -[ABKService request:finishedSuccessfully:] + 279
	26  Application                            0x0000000104106f4a __29-[ABKService processRequest:]_block_invoke.493 + 634
	27  CFNetwork                           0x000000010ab19208 __75-[__NSURLSessionLocal taskForClass:request:uploadFile:bodyData:completion:]_block_invoke + 19
	28  CFNetwork                           0x000000010ab18a6d __49-[__NSCFLocalSessionTask _task_onqueue_didFinish]_block_invoke + 147
	29  Foundation                          0x00000001057f39b7 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 7

Could you help me please?

I use iOS 10, 11. SDK version 3.1.0, Integrated with cocoapods, Xcode 8.3.3 and 9.0, reproduce all  the time.

**Comment by semionenko** [comment] 2017-10-09 06:18
![screen shot 2017-10-09 at 13 17 34](https://user-images.githubusercontent.com/3960765/31326747-46486aea-acf4-11e7-8222-2d01f271e5a7.png)

Attached the card for reproduce.

**Comment by tiffanylu** [comment] 2017-10-09 16:32
Hi @semionenko,

Thanks for opening this issue! A few follow-up questions:

1. Could you please provide us with your app's Podfile?
2. Are you using NUI? If so, could you provide your app's NUI stylesheet? 

Lastly, if you're able to provide us with a sample application that reproduces this issue, it would be helpful for our debugging.

Thanks!
Tiff

**Comment by semionenko** [comment] 2017-10-10 01:45
[Archive.zip](https://github.com/Appboy/appboy-ios-sdk/files/1370299/Archive.zip)
Yes, sure.

`[Appboy startWithApiKey:@"<KEY>" inApplication:application withLaunchOptions:launchOptions];
[Appboy sharedInstance].appboyUrlDelegate = self;
[NUISettings initWithStylesheet:@"ApplicationNUIStyle"];
[Appboy sharedInstance].useNUITheming = YES;`

The other code is above.

**Comment by tiffanylu** [comment] 2017-10-10 01:57
Hi @semionenko,

If you don't use NUI, does the crash still occur? 

Also, it looks like your NUI stylesheet lists `font-name: AvenirNext-Semibold` under `ABKFeedItemTitleLabel`  and in a few other places. It looks like the system font may be titled `AvenirNext-DemiBold` instead. Does changing this solve the problem?

Best,
Tiff

**Comment by semionenko** [comment] 2017-10-10 02:04
Yes, you're right. All problems in wrong font name. Thanks!

p.s.: it is probably worth adding a warning if sdk can not find the font?

**Comment by tiffanylu** [comment] 2017-10-10 19:40
Glad to hear that solved the problem, @semionenko! I'm going to close this issue given the resolution, and our team will add protection around this in our SDK moving forward. Thanks again for reporting!

**Closed by tiffanylu** 2017-10-10 19:40 UTC
