### ISSUE TITLE
Crash in [ABKPushSettings fetchCurrentPushSettingsWithFlush:]

### ISSUE THREAD

**Issue by mggeray** [Appboy/appboy-ios-sdk#150] opened 2018-05-29 14:19 UTC
We had a crash in production but unfortunately I don't know how this can be reproduced. The crash happened 9 times. 

The crash seems to happen here:
>16 Appboy_iOS_SDK                 0x1029e935c +[ABKPushSettings fetchCurrentPushSettingsWithFlush:] (ABKPushSettings.m:20)
>17 Appboy_iOS_SDK                 0x102939b90 -[Appboy startSession] (Appboy.m:442)
>18 Appboy_iOS_SDK                 0x10293764c +[Appboy startWithApiKey:inApplication:withLaunchOptions:withAppboyOptions:] (Appboy.m:187)
>19 Appboy_iOS_SDK                 0x10293779c +[Appboy startWithApiKey:inApplication:withLaunchOptions:] (Appboy.m:199)

Info | Value
------------ | -------------
Platform Name | iOS
OS Version | 11.2.6
SDK Version | 3.2.3
Integration Method | cocoapods

**Comment by chshapiro** [comment] 2018-05-30 17:46
Hey @mggeray ,

Unfortunately we're unable to reproduce this issue. Can you provide us with the full stack trace so we can investigate further?

If you don't feel comfortable putting this info in our public repo, feel free to email support@braze.com with this information.

Thanks,
Chava

**Comment by chshapiro** [comment] 2018-06-19 15:56
@mggeray, closing for now. Please reopen the issue if you have any further questions. Thanks!

**Closed by chshapiro** 2018-06-19 15:56 UTC
