### ISSUE TITLE
iOS Deprecated API Usage Warning

### ISSUE THREAD

**Issue by miquelalvarado** [Appboy/appboy-ios-sdk#198] opened 2019-08-29 14:11 UTC
Just submitted my app to TestFlight and got an email with the error:

ITMS-90809: Deprecated API Usage - Apple will stop accepting submissions of apps that use UIWebView APIs . See https://developer.apple.com/documentation/uikit/uiwebview for more information.

I was wondering if all the code related to UIWebView will have to be removed and only keep WKWebView.

It was just a warning, the build ended up being available on TestFlight, but I think this is something that will have to be addressed at some point.

**Comment by chshapiro** [comment] 2019-08-29 14:37
Hey @miquelalvarado ,

We are working on prioritizing this and will keep you updated on this thread.

Thanks!

**Comment by gringoireDM** [comment] 2019-08-30 14:14
```
#pragma clang diagnostic ignored “-Wdeprecated-declarations”
```

Usually it's a good idea to address deprecation in time, instead of hiding them

**Comment by chshapiro** [comment] 2019-08-30 19:49
Hey @gringoireDM, 

We are working on a fix that will address the root cause and replace UIWebView with WKWebView. We will keep this thread updated when we release the fix. 

Thanks!

**Comment by gringoireDM** [comment] 2019-09-04 12:46
Hi, what's the status on this? Please let us know if you need any help because we cannot afford to risk gettin our apps rejected for this.

**Comment by chshapiro** [comment] 2019-09-04 13:59
Hey @gringoireDM,

This is our top priority and we are actively working on it. The change will be included in our next release.

**Comment by Frankiim** [comment] 2019-09-06 15:10
Hi @chshapiro 

Do you have a rough ETA for when the next release will be and when the React Native SDK will be updated with the same please?

**Comment by swillsea** [comment] 2019-09-10 20:57
@chshapiro It looks like your latest release (3.19) fixes this. Can this issue be closed out?

**Comment by Bucimis** [comment] 2019-09-10 21:01
@Frankiim @swillsea @gringoireDM @miquelalvarado thank you all for raising and participating in this discussion. We just released iOS SDK 3.19.0 which replaces all usages of `UIWebView` with `WKWebView`. Note that there is a breaking behavioral change here - the following javascript methods are now no-ops following the release: `alert`, `confirm`, `prompt`.

Please reach out again if you continue to experience issues & thanks again!

**Closed by Bucimis** 2019-09-10 21:01 UTC

**Comment by robertmusialek** [comment] 2019-09-13 08:00
Hey,
I've got a question regarding something that was written in changelog for `3.19.0` release:

> If you are using ATS in your app, add the NSAppTransportSecurity dictionary to your Info.plist file. Inside the dictionary, add the NSAllowsArbitraryLoads boolean subentry and set the value to YES.

According to Apple's documentation this should be avoided:

> Important
> You must supply a justification during App Store review if you set the key’s value to YES, as described in Provide Justification for Exceptions. Use this key with caution because it significantly reduces the security of your app. In most cases, it’s better to upgrade your servers to meet the requirements imposed by ATS, or at least to use a narrower exception.

What is the impact of not following with your _adivce/requirement_ and not setting `NSAllowsArbitraryLoads` to `YES`?
Can this issue be solved by adding exceptions for your domains? What would be those domains in that case?

cheers,
R

**Comment by bpapa** [comment] 2019-09-13 15:51
Adding arbitrary loads isn't going to fly with App Review. Braze is going to need to provide the specific domains.

**Comment by Bucimis** [comment] 2019-09-13 19:20
@robertmusialek @bpapa there's no need to set `NSAllowsArbitraryLoads` to `YES`. That documentation was added in error and has been removed, our apologies for the misdirection.
