### ISSUE TITLE
Crashes on 2.19.1 version

### ISSUE THREAD

**Issue by hovox** [Appboy/appboy-ios-sdk#63] opened 2016-04-22 12:58 UTC
Hi,

We have 2 crashes related to Appboy, which are our top two crashes.

Here they are

[http://crashes.to/s/996598399e3](http://crashes.to/s/996598399e3)
[http://crashes.to/s/90faa0fa12f](http://crashes.to/s/90faa0fa12f)

Is this crashes are fixed in 2.19.2 version ?

**Comment by Wenzhi** [comment] 2016-04-22 14:12
Hi @hovox ,

Thanks for reporting this issue - it seems that the crashes happen when a user has no session and no network connection.

This is unexpected as we always keep at least one session for each user. Can you provide us more information:
* Have you reproduced the crash? Could you share the steps to reproduce?
* Where do you call the `startWithAPIKey:` method? Do you do any customization for Appboy, like setting a request flushing policy?
* Appboy starts a new session in two cases: when `startWithAPIKey` is called, or when UIApplicationWillEnterForegroundNotification arrives. Do you also listen to UIApplicationWillEnterForegroundNotification? 

Thanks,
Wenzhi

**Comment by hovox** [comment] 2016-04-22 14:22
Hi @Wenzhi 

Thanks for your response

We can't reproduce the crash.
startWithApiKey: called in appdelegate here is the call

```
    [Appboy startWithApiKey:key
              inApplication:[UIApplication sharedApplication]
          withLaunchOptions:launchOptions
          withAppboyOptions:@{ABKRequestProcessingPolicyOptionKey: @(ABKAutomaticRequestProcessing),
                              ABKSessionTimeoutKey : @(30)}];
```

No, we are not doing any appboy specific things in UIApplicationWillEnterForegroundNotification.

**Comment by Wenzhi** [comment] 2016-04-22 14:29
Hi @hovox, 

Thanks for the code. We will continue the investigation and add protection against these cases to handle the crashes in the SDK. 

Thanks,
Wenzhi

**Comment by hovox** [comment] 2016-04-22 14:30
So updating to 2.19.2 will not fix the issue ?

**Comment by Wenzhi** [comment] 2016-04-22 15:35
2.19.2 does not contain the fix for this.  We’re actively investigating and will update ASAP.

**Comment by Wenzhi** [comment] 2016-04-25 20:16
Per our offline discussion, guarding around this issue has been added and will be released this week in our SDK; we will continue to investigate the cause.  Thanks again for reporting and please let us know if you have any further comments/questions.

**Comment by Wenzhi** [comment] 2016-04-27 01:27
Hi @hovox,

The new release 2.19.3 with the crash fix is out now. I'm going to close this issue. Please let us know or re-open this issue if you see the same crash happens again.

Thanks,
Wenzhi

**Closed by Wenzhi** 2016-04-27 01:27 UTC
