### ISSUE TITLE
beforeInAppMessageDisplayed:withKeyboardIsUp: method is not being called

### ISSUE THREAD

**Issue by anna-sakhlyan** [Appboy/appboy-ios-sdk#109] opened 2017-05-12 15:14 UTC
Platform Name            ios 
 Platform Version         greater than 10
 SDK Version                doesn't metter (tested with 2.25.0 version and latest 2.29.1 version)
 Integration Method    cocoapods 
 Xcode Version            doesn't metter (tested on Version 8.2.1 and on latest version)
 Repro rate                   all the time

beforeInAppMessageDisplayed:withKeyboardIsUp: method is not being called for devices greater than iOS 10 when using UserNotifications framework’s  userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler method. Everything works fine when the latter method is not used.

**Comment by Wenzhi** [comment] 2017-05-12 15:23
Hey @anna-sakhlyan, 

Could you provide more detail about your use case of the in-app message and push, as well as how you integrate the in-app message(e.g. where you set the in-app message delegate)? It's unclear to me how the integration choice of remote notification affects the in-app message integration.

Please follow the issue template:
## What did you do?
ℹ Please replace this with what you did.  

## What did you expect to happen?
ℹ Please replace this with what you expected to happen.  

## What happened instead?
ℹ Please replace this with what happened instead.  

## Steps to reproduce
ℹ Please give us detailed steps so we can reproduce the issue on our end. This is very important and will help speed up the investigation a lot.

Thanks,
Wenzhi

**Comment by anna-sakhlyan** [comment] 2017-05-12 16:36
I have integrated in app messages in a custom way.
I’m not using Appboy SDK’s UI and instead presenting my custom controllers in `beforeInAppMessageDisplayed:withKeyboardIsUp:` method

I set `[Appboy sharedInstance].inAppMessageController.delegate = self` in my App delegate’s
`application:didFinishLaunchingWithOptions:launchOptions` method.

It’s strange for me as well. It’s unclear to me how my in-app messages integration is related to this.
And again it works fine when I’m testing this on iOS 9 with or without UserNotification framework. Problem is only on iOS 10 and above.

**Comment by Wenzhi** [comment] 2017-05-12 17:38
Hey @anna-sakhlyan,

Could you provide the code snippets of your methods `application:didFinishLaunchingWithOptions:`, `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:` and `application:didReceiveRemoteNotification:fetchCompletionHandler:`?

One case we saw was that the in-app message came in before the delegate was set. In that case, you can set the in-app message's delegate in the `appboyOptions` with key `ABKInAppMessageControllerDelegateKey` when you call `startWithApiKey:inApplication:withLaunchOptions:withAppboyOptions`. Could you try it out and see if it solves the issue?

Thanks,
Wenzhi

**Comment by anna-sakhlyan** [comment] 2017-05-15 08:41
```
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions {
    [Appboy startWithApiKey:key
              inApplication:[UIApplication sharedApplication]
          withLaunchOptions:launchOptions
          withAppboyOptions:@{ABKRequestProcessingPolicyOptionKey: @(ABKAutomaticRequestProcessing),
                              ABKSessionTimeoutKey : @(30)}];
    AppboyEndpointDelegate *endpointDelegate = [[AppboyEndpointDelegate alloc] init];
    [Appboy sharedInstance].appboyEndpointDelegate = endpointDelegate;
    [Appboy sharedInstance].useNUITheming = NO;
    [Appboy sharedInstance].inAppMessageController.delegate = self;
}
```
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)())completionHandler {
      [[Appboy sharedInstance] userNotificationCenter:center didReceiveNotificationResponse:response withCompletionHandler:completionHandler];
}
```
```
 -(void)application:(UIApplication *)application didReceiveRemoteNotification:(NSDictionary *)userInfo fetchCompletionHandler:(void (^)(UIBackgroundFetchResult))completionHandler  {
     [[Appboy sharedInstance] registerApplication:application didReceiveRemoteNotification:userInfo fetchCompletionHandler:completionHandler];
}
```
After sending in app message, the app called 
`application:didReceiveRemoteNotification: fetchCompletionHandler:`
and I’m getting notification from AppBoy 
```
didReceiveRemoteNotification {
    ab =     {
        c = "<null>";
    };
    "ab_push_fetch_test_triggers_key" = 1;
    aps =     {
        alert = "Click to see Test In-App Message";
        badge = 1;
    };
}
```

In this method, `[Appboy sharedInstance].inAppMessageController.delegate` is set correctly
then Appboy must call the 
`beforeInAppMessageDisplayed:withKeyboardIsUp:`
but it is not called

When remove the following method and run the app again, it works correct.
 `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`

I also tried to set appboyOptions with the key ABKInAppMessageControllerDelegateKey, as you suggested but that didn’t help.

**Comment by hovox** [comment] 2017-05-16 07:33
Hi @Wenzhi . Any news on this issue ?

**Comment by anna-sakhlyan** [comment] 2017-05-16 10:05
I've created an example project for you to help solve the problem we are dealing with. Though the Appboy in-app messages implementation is not customised the problem is still there. https://github.com/anna-sakhlyan/AppboyTest

**Comment by tiffanylu** [comment] 2017-05-16 17:27
Hey @anna-sakhlyan,

The sample application that you sent us doesn't import the UserNotifications framework in the `AppDelegate`. Could you add `#import <UserNotifications/UserNotifications.h>` to your `AppDelegate` and see if it works?

Best,
Tiff

**Comment by hovox** [comment] 2017-05-16 19:05
Hi @tiffanylu. I'm working with @anna-sakhlyan. You are right `#import <UserNotifications/UserNotifications.h>` not imported in app delegate. But it's imported in our app.

Could you please explain how it will help ? Without importing it code compiles and runs.

Thanks in advance

**Comment by tiffanylu** [comment] 2017-05-16 20:24
Hi @hovox and @anna-sakhlyan,

Apologies for the misleading question earlier. Could you implement the `userNotificationCenter:willPresentNotification:withCompletionHandler:` delegate method in your application and see if the in-app message delegate gets called afterwards? Our SDK does not handle notifications received in `application:didReceiveRemoteNotification:fetchCompletionHandler:` if the `UserNotifications` delegate is set. However, when the app is foregrounded and `userNotificationCenter:willPresentNotification:withCompletionHandler:` is not implemented, the system appears to call `application:didReceiveRemoteNotification:fetchCompletionHandler:` instead of `userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:`. 

Sample code for displaying notifications in the foreground:
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center
       willPresentNotification:(UNNotification *)notification
         withCompletionHandler:(void (^)(UNNotificationPresentationOptions options))completionHandler {
  completionHandler(UNNotificationPresentationOptionAlert);
}
```


Please let us know if making this change works for you, and we can update our documentation accordingly.

Best,
Tiff

**Comment by anna-sakhlyan** [comment] 2017-05-17 12:33
Hi @tiffanylu 

I’ve updated the example project and added `userNotificationCenter:willPresentNotification:withCompletionHandler `. Now we are receiving push notification like UI alert and after clicking on that alert we are receiving in-app message.
Now the problem is that we don’t want to show the alert when user is using the app. Is there any way we can skip this and show the in-app message instead? Basically we want the same behaviour as on iOS 9, where the in-app alert is not shown before in-app message.  

![screen shot 2017-05-17 at 4 32 37 pm](https://cloud.githubusercontent.com/assets/20638205/26153907/7aafc29e-3b1e-11e7-9d1c-7192f08925cf.png)

**Comment by chshapiro** [comment] 2017-05-17 15:47
Hey @anna-sakhlyan,

The reason the alert is showing before the in-app message is because this is a test message. The way we send test messages is through a push which shows the in-app message once the push is clicked. Unfortunately, if you suppress the display of the push notification, neither push delegate will be called and the test in-app message will not be shown.

However, once the app is in production and the campaign is live, the in-app message will show on its own as triggered without an alert showing before it. This behavior is restricted to test messages only. You can confirm this by testing with campaigns vs. test messages.

We will look into ways to update our handling to account for this case, although we do not currently have a set timeline for that investigation.

Please let us know if you have any more questions.

Thanks,
Chava

**Comment by anna-sakhlyan** [comment] 2017-05-18 11:19
Hi @chshapiro 

Thank you for yours and your teams help on this. We were able to fix the issue. If we have any new developments I will be sure to let you know.

Kind Regards
Anna

**Comment by tiffanylu** [comment] 2017-05-18 14:24
Glad to hear that, @anna-sakhlyan! Did you find a way to make test in-app messages display without showing the notification in the foreground, or were you able to get the behavior you wanted in production instead?

I'm going to close this issue since it sounds like everything is good here, but feel free to reopen if you have any additional questions.

Best,
Tiff

**Closed** 2017-05-18 14:24 UTC
