### ISSUE TITLE
Crash in `ABKTriggeredAction setEndTime:` => `NSOperationQueue QOS: UNSPECIFIED`

### ISSUE THREAD

**Issue by mathaeus** [Appboy/appboy-ios-sdk#137] opened 2018-01-02 09:13 UTC
Hi, see the attached crash report for a crash that occurred for our app. Unfortunately I don't have more information. It happened right after app start.

`Crashed: NSOperationQueue 0x1c4039440 (QOS: UNSPECIFIED)
0  Appboy_iOS_SDK                 0x1011eb000 -[ABKTriggeredAction setEndTime:] + 66
1  Foundation                     0x187874f9c _encodeObject + 1212
2  Foundation                     0x187876508 -[NSKeyedArchiver _encodeArrayOfObjects:forKey:] + 440
3  Foundation                     0x187874f9c _encodeObject + 1212
4  Foundation                     0x18787c230 +[NSKeyedArchiver archivedDataWithRootObject:] + 168
5  Appboy_iOS_SDK                 0x1011bcbf0 -[ABKTriggerManager synchronizeTriggerActionsToUserDefaults] + 172
6  Appboy_iOS_SDK                 0x1011babcc __53-[ABKTriggerManager receiveTriggersFromNotification:]_block_invoke + 168
7  Foundation                     0x1878f6310 __NSBLOCKOPERATION_IS_CALLING_OUT_TO_A_BLOCK__ + 16
8  Foundation                     0x1878369e4 -[NSBlockOperation main] + 72
9  Foundation                     0x187826620 -[__NSOperationInternal _start:] + 848
10 libdispatch.dylib              0x1868b1048 _dispatch_client_callout + 16
11 libdispatch.dylib              0x1868b86c8 _dispatch_block_invoke_direct$VARIANT$mp + 288
12 libdispatch.dylib              0x1868b1048 _dispatch_client_callout + 16
13 libdispatch.dylib              0x1868b86c8 _dispatch_block_invoke_direct$VARIANT$mp + 288
14 libdispatch.dylib              0x1868b8574 dispatch_block_perform$VARIANT$mp + 104
15 Foundation                     0x1878f7fe8 __NSOQSchedule_f + 376
16 libdispatch.dylib              0x1868b1048 _dispatch_client_callout + 16
17 libdispatch.dylib              0x1868b93d4 _dispatch_continuation_pop$VARIANT$mp + 428
18 libdispatch.dylib              0x1868b7cd4 _dispatch_async_redirect_invoke$VARIANT$mp + 604
19 libdispatch.dylib              0x1868be1c8 _dispatch_root_queue_drain + 596
20 libdispatch.dylib              0x1868bdf10 _dispatch_worker_thread3 + 120
21 libsystem_pthread.dylib        0x186b57130 _pthread_wqthread + 1268
22 libsystem_pthread.dylib        0x186b56c30 start_wqthread + 4`

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 11.0.3 (15A432)
Device | iPhone 6
 SDK Version             |3.2.2
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9.2
 Repro rate              | only once

**Comment by Wenzhi** [comment] 2018-01-02 22:00
Hey @mathaeus,

Thanks for reporting the crash! 

From the crash report, it seems that something was wrong when the SDK tried to unarchive a trigger object. However, I need to see the error message to tell what's the issue. It can be caused by data corruption or a potential SDK bug.

Could you tell me more about the crash like:
- Where did you see the error, in a production or a development app? 
- Did you see the crash or it is from one of your users?
- Can you reproduce the crash by any chance?
- Do you have the entire crash report file?

If this happened during your app development, my suggestion is to try to uninstall and reinstall the app and see if you can catch the same crash. Uninstall and reinstall the app should remove the potentially corrupted data. Please let us know if you see the same crash happen again.

Thanks,
Wenzhi

**Comment by mathaeus** [comment] 2018-01-03 11:33
Sent you an email with the detailed crash report.

**Comment by chshapiro** [comment] 2018-04-11 14:39
@mathaeus closing for now. Please reopen the issue if the issue recurs or worsens or if you have any further questions. Thanks!

**Closed by chshapiro** 2018-04-11 14:39 UTC
