### ISSUE TITLE
ABKSessionTimeoutKey not found with Swift 2.2

### ISSUE THREAD

**Issue by justin** [Appboy/appboy-ios-sdk#56] opened 2016-03-22 15:47 UTC
If you generate `Appboy.h`'s Swift interface in Xcode 7.3 and Swift 2.2, your external constants are no longer visible. 

We rely on updating that timeout value in our app, and are blocked by it in our Swift 2.2 push management classes now. 

Thanks!

**Comment by briancaw** [comment] 2016-03-22 17:09
Thanks for reporting @justin.  We're actively looking into this and will communicate timing for a release in the near future.

**Comment by Wenzhi** [comment] 2016-03-28 15:51
Hi @justin,

I just tested our sample swift project in Xcode 7.3 and Swift 2.2, also created a brand new swift project to test, but I didn't have any issue using `ABKSessionTimeoutKey`. 

May I ask if you integrated Appboy following [our documentation](https://documentation.appboy.com/iOS/#step-4-updating-your-app-delegate)? If not, could you give me more detail about your integration so I can reproduce your issue?

Thanks,
Wenzhi

**Comment by justin** [comment] 2016-03-28 16:23
We don't use Cocoapods. We are using the [manual integration setup][manual] and have AppboyKit imported via our ObjC bridging header.

When you try to create the Generated interface for `Appboy.h` do you see the `extern NSString *const` keys? We see none of them. 

<img width="184" alt="screen shot 2016-03-28 at 10 22 15 am" src="https://cloud.githubusercontent.com/assets/1384/14082762/fe8c93ea-f4ce-11e5-8a11-6838d45a7c1e.png">



[manual]: https://documentation.appboy.com/iOS/#manual-sdk-integration

**Comment by briancaw** [comment] 2016-03-29 21:47
Hey @justin 

I can reproduce this on a manual integration for Swift 2.2.  The problem is that those variables are defined inside the @interface tag in `Appboy.h`.  You should be able to move them outside the interface and then see them become available.

Please let us know if this solves your issue; if it does, it would be good to know if you can use a locally modified SDK until our next planned release (3 weeks) or if you'd require a release sooner.

Thanks,
Brian

**Comment by johannth** [comment] 2016-03-31 10:35
This also affects `ABKUserGenderType` and `ABKNotificationSubscriptionType` which are declared within the `@interface` tag of `ABKUser.h`. You can still use `ABKUser` in Swift but we need to subclass it in Swift for testing purposes and then the `ABKUserGenderType` is undeclared.

**Comment by briancaw** [comment] 2016-03-31 11:17
Hy @johannth 

Thanks very much for reporting - we've also got those moved out of the interface tag now and will have that as part of the release that fixes this issue.

**Comment by justin** [comment] 2016-03-31 14:16
We release at the first of the month, but we can survive until our May release if the timing doesn't work.

**Comment by briancaw** [comment] 2016-04-01 20:40
Hey All,

This is fixed in version 2.19.2 that just went live.  Please reopen and let us know if you run into any further issues.

Thanks,
Brian

**Closed by briancaw** 2016-04-01 20:40 UTC
