### ISSUE TITLE
Facebook selection issue on FeedbackViewController

### ISSUE THREAD

**Issue by tamaragevorgyan** [Appboy/appboy-ios-sdk#34] opened 2015-09-30 06:53 UTC
Hi all,

I have a problem with my feedback page when trying to send feedback using Facebook info.
The “Enable Facebook Connection” error message appears for each time after tapping on the “Facebook” icon in the “Feedback” page and user is unable to provide contact info from “Facebook”. 
![img_6893](https://cloud.githubusercontent.com/assets/6357138/10186356/0f11c7fc-6759-11e5-9d55-025a32db6d1d.PNG)

**Comment by Wenzhi** [comment] 2015-09-30 18:31
Hi @tamaragevorgyan,

The issue is due to an Apple's bug. Appboy only displays the Facebook button on the feedback page when the user's Facebook information is accessible from the iOS system. However, when there’s no Facebook details in the iOS Settings but the user has the Facebook app installed, `[SLComposeViewController isAvailableForServiceType:SLServiceTypeFacebook]` will always return YES, which leads to the error.

We are discussing the best solution for this right now and will provide an update soon.

Thanks,

**Comment by Wenzhi** [comment] 2015-11-17 16:32
Hi @tamaragevorgyan, we removed the Facebook button in the new released SDK version 2.17. So your issue should be fixed now as there is no Facebook button on the Feedback page anymore.

I'm closing the issue. Please let me know if you have any other questions.

**Closed by Wenzhi** 2015-11-17 16:32 UTC

**Comment by tamaragevorgyan** [comment] 2015-11-17 17:38
Hi, thanks for your support and attention, I will update our SDK to lat one and give you feedback.

Regards,
Tamara.
