### ISSUE TITLE
Appboy-Push-Story support bitcode?

### ISSUE THREAD

**Issue by mugcookie** [Appboy/appboy-ios-sdk#172] opened 2018-12-28 07:17 UTC
I try to install Appboy-Push-Story into my project via cocoapod.

target 'My App Notification Content Extension' do
    use_frameworks!
    pod 'Appboy-Push-Story', '~>3.0'
end

But When I attempt to archive, I get the following error message:
ld: bitcode bundle could not be generated because '[...]/AppboyPushStory.framework/AppboyPushStory' was built without full bitcode. All frameworks and dylibs for bitcode must be generated from Xcode Archive or Install build for architecture armv7

Any advice on how to proceed?

**Comment by chshapiro** [comment] 2018-12-28 17:57
Hey @mugcookie ,

We are working on a fix for this and it will be included in our next release.

Please let us know if you have any further questions.

Thanks,
Chava

**Comment by scottlemke** [comment] 2019-01-18 16:14
`3.12.0` states that it fixed this issue, but I'm still seeing this error: `AppboyPushStory.framework/AppboyPushStory' was built without full bitcode.` This is after pulling version `3.12.0` of the Appboy-iOS-SDK and Appboy-Push-Story pods.

Is there something I'm doing wrong, possibly?

**Comment by Bucimis** [comment] 2019-01-18 22:33
HI @scottlemke, thanks for bringing this to our attention - the issue is on our end.

As of now we've reproduced the issue and implemented a fix. We're still validating the fix and will provide further confirmation and instructions when it's ready - aiming for no later than Tuesday after the long weekend. (If you'd like to preview the fix, you can try deleting your Cocoapods cache at `${HOME}/Library/Caches/CocoaPods`, re-installing `3.12.0`, and archiving - note that the correct push stories executable should be about 2.5mb)

Thanks again

**Comment by scottlemke** [comment] 2019-01-22 22:36
Hi @Bucimis. This appears to have fixed my issue. Thank you!

**Comment by Bucimis** [comment] 2019-01-22 22:43
Hi @scottlemke great, thank you for following up!

**Closed by Bucimis** 2019-01-22 22:43 UTC
