### ISSUE TITLE
Deeplink pushes calls openUrl twice when app is completely closed (on >iOS10 devices)

### ISSUE THREAD

**Issue by nfrydenholm** [Appboy/appboy-ios-sdk#170] opened 2018-12-14 13:07 UTC
* [ ] I have checked [Braze's documentation](https://www.braze.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | iOS
 Platform Version        | 10.0+
 SDK Version             |  3.10.0
 Integration Method      |  cocoapods / 
 Xcode Version           | Xcode 10.1
 Repro rate              | all the time (100%) 
 
## What did you do?

When sending out a push with a deeplink to open the app, openUrl is called twice, when the app is "cold started" (completely shut down).

## What did you expect to happen?
That my app only is invoked with a deeplink once.

## What happened instead?
My AppDelete openUrl method is invoked twice

## Steps to reproduce
Follow the setup documentation, and make sure 
both this  `[Appboy startWithApiKey:inApplication:withLaunchOptions:];`

and the `    [[Appboy sharedInstance] userNotificationCenter:center
                     didReceiveNotificationResponse:response
                              withCompletionHandler:handler];`
is called.

Close the app completely, and send a push with a deeplink to the app.

## Workaround
If I make sure not to send in the launchOptions to Appboy, my app works as expected and the openUrl is only invoked once.
 I assume it's becasue the Appboy SDK is using pushMessage stored in the launchOptions, which is only needed < iOS 10. So when it runs on a iOS 10 device, and the UNNotificatoinCenter is used, it seems wrong to also use the launchOptions.

**Comment by Bucimis** [comment] 2018-12-14 18:46
Hi @nfrydenholm, we were not able to reproduce this behavior. A few thoughts:
1) You should make always make sure to pass `launchOptions` into `didFinishLaunching` to ensure direct opens work as expected.
2) You should ensure the routing logic in your `openUrl` implementation doesn't inadvertently lead to another call to `openUrl`. See https://github.com/BranchMetrics/ios-branch-deep-linking/issues/361 for more
3) Are you using `ABKURLDelegate`? If so, is `handleAppboyURL` also being called twice?

**Comment by nfrydenholm** [comment] 2018-12-17 20:54
Hi
I'm out of office until Wednesday, but I'll try to look at it again, and see if I can reproduce it in a sample app.
1. I can only avoid the double openUrl if I currently don't pass in the launchOptions.
2. I have checked that already. If I send out the same deeplink url through Firebase, the app handles it as expected with only one call to openUrl.
3. We don't use the ABKUrlDelegate.

**Comment by Bucimis** [comment] 2018-12-17 22:45
@nfrydenholm if you are able to create a sample project that repros the issue and send it over, that would help tremendously. enjoy the time off!

**Comment by nfrydenholm** [comment] 2019-01-08 17:38
Thanks for the follow up on this @Bucimis 
I'm currently off work due to a broken leg, so I haven't been able to look more into it. :(

Once I'm on less morphine, I'll see if I can have a look to see if I can reproduce it in an example app.

Is there a "demo" apikey and custom endpoint I can use for a demo-application to be able to send remote notifications to it?

**Comment by Bucimis** [comment] 2019-01-08 22:00
@nfrydenholm sorry to hear that, hope you feel better soon! For the demo, feel free to ship it to us without credentials, we'll add those ourselves if necessary.

**Comment by nfrydenholm** [comment] 2019-01-28 14:22
I'm still off work, but looked at this issue again. I realised it seems like quite a lot of work to setup a demo app with profiles, certificates, push etc. to be able to pull off a demo app that can run on a device.
So I haven't done that yet - instead I've looked through our app, to ensure we don't have any place where we ourselves call UIApplication.open(url...)
We have an extension for that openUrl method, and it's only through that extension we make use of openUrl. I've added some logging in there, and it doesn't show up in the console. 

Instead I have these two log-sequences - one where I provide the launch options to Appboy SDK, and one where I set it to nil. 

My steps to reproduce

- close the app completely
- Log in to braze.com and create a new iOS-push-campaign
-  Write a hello world message and set the Push notification body to "Deep link into application"
- Provide a valid deep link url for our app
- Send it to my specific device with the closed app
- Verify that the app is started twice when launchoptions are provided to the Appboy SDK

First attempt when providing the launchOptions:
```
14:43:57.628 ~0303 DBABrazeManager:030 DEBUG] [BRAZE] Appboy StartWithApiKey + include LaunchOptions!
[14:43:57.642 ~0303 DBABrazeManager:076 DEBUG] [BRAZE] call Appboy sdk userNotificationCenter didReceiveNotificationResponse
[14:43:57.951 ~0303  dbaAppDelegate:197 DEBUG] [BRAZE] application openUrl dba://www.dba.dk/til-boligen/glas-porcelaen-og-bestik/glas-porcelaen-og-bestik/
[14:43:59.429 ~0303  dbaAppDelegate:197 DEBUG] [BRAZE] application openUrl dba://www.dba.dk/til-boligen/glas-porcelaen-og-bestik/glas-porcelaen-og-bestik/
``` 

Second attempt when setting launchOptions to nil for the Appboy SDK initialization
```
[14:47:41.189 ~0303 DBABrazeManager:030 DEBUG] [BRAZE] Appboy StartWithApiKey + set LaunchOptions to nil!
[14:47:41.205 ~0303 DBABrazeManager:076 DEBUG] [BRAZE] call Appboy sdk userNotificationCenter didReceiveNotificationResponse
[14:47:41.509 ~0303  dbaAppDelegate:197 DEBUG] [BRAZE] application openUrl dba://www.dba.dk/til-boligen/glas-porcelaen-og-bestik/glas-porcelaen-og-bestik/
``` 

The `application openUrl` log-statements are from the Appdelegate, when the app is invoked with an Url. There is no sign of my logging from our own OpenUrl extension, so we don't have any code where we extract the deeplink url from the message, and is trying to do something about it.

It's "only" a problem when the app is completely closed, which is where the launchOptions also contains the `UIApplicationLaunchOptionsRemoteNotificationKey`

**Comment by Bucimis** [comment] 2019-01-28 21:00
@nfrydenholm thanks for following up, this is helpful and agreed that creating a sample app with push can be a prohibitive amount of work.

Could you send us the full context of the code that calls `[BRAZE] application openUrl`? I want to see how and when that's logged. Feel free to redact anything sensitive or, alternatively, email support@braze.com if you'd prefer to share that code through a more secure channel.

**Comment by nfrydenholm** [comment] 2019-01-29 07:50
Here is a bit more context from the places where the logging takes place. 
The initialization of the Appboy SDK is done in didFinishLaunchingWithOptions, and the other places the code looks like this

The userNotification method normally has an if/else logic to determine if the message is from Braze or Firebase. I have removed that for clarity.
```
- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))handler
{	
    logDebug(@"[BRAZE] call Appboy sdk userNotificationCenter didReceiveNotificationResponse");
    [[Appboy sharedInstance] userNotificationCenter:center
                     didReceiveNotificationResponse:response
                              withCompletionHandler:handler];

}
``` 

And the application openUrl comes from this method in the appDelegate
```
- (BOOL)application:(UIApplication *)app openURL:(NSURL *)url options:(NSDictionary<NSString *, id> *)options
{
    logDebug(@"[BRAZE] application openUrl %@", url.absoluteString]);
    if (url) {
    	//Do our internal logic to parse the url, and open the correct ViewController
    }
    else
        return NO;
}
```

**Comment by Bucimis** [comment] 2019-01-30 00:07
@nfrydenholm thanks for following up. We replicated this set up and weren't able to reproduce the `openURL` application delegate being called multiple times. Is it possible that somewhere within your `openURL` or `ABKURLDelegate` implementation, you're calling `openURL` manually? Note that in it's standard handling of deep links, Braze will call `[UIApplication sharedApplication] openURL` once, so if you call it as well, the `openURL` delegate will fire twice.

**Comment by nfrydenholm** [comment] 2019-01-30 16:54
That is weird 🤔 

We don't implement/use `ABKURLDelegate` and I have been through the entire app looking for usage of `[UIApplication sharedApplication] openURL` and we only call that within an Extension, which is never invoked when opening a Braze push (besides that, we don't have any logic in place to extract the Url from a Braze push, so I don't have the url to actually open).

How do you determine in the SDK (it might be a secret, you don't want to reveal here :) ) if you should extract the PushNotification from the launchOptions (UIApplicationLaunchOptionsRemoteNotificationKey)  and actually do something with it? 

We used to use that launchArgument as well well for iOS < 10, to make sure we would handle push messages when the App was completely closed, but since iOS10 is now the minimum we support, we removed the logic to extract anything from launchArguments, because it is now being handled in the 
`- (void)userNotificationCenter:(UNUserNotificationCenter *)center didReceiveNotificationResponse:(UNNotificationResponse *)response withCompletionHandler:(void (^)(void))handler` 

So I'm wondering if your logic is looking at the iOS version, and maybe whether a delegate has been set on the UNUserNotificationCenter? (I set a delegate on the UNUserNotificationCenter before the Appboy SDK is started with the launchOptions)

I'm just trying to think out loud 😄

**Comment by Bucimis** [comment] 2019-01-31 02:38
@nfrydenholm "I set a delegate on the UNUserNotificationCenter before the Appboy SDK is started with the launchOptions" seems OK. 

As you guessed, we extract the push payload in `didFinishLaunchingWithOptions` using `UIApplicationLaunchOptionsRemoteNotificationKey`. However, we have a check in our `didFinishLaunchingWithOptions ` push handling code that cancels handling push if `UNUserNotificationCenter` delegates are present.

The following method should return `true` in your app when you call `startWithApiKey` to ensure we don't do any push handling in `didFinishLaunchingWithOptions `:

```
// don't handle push from didFinishLaunchingWithOptions if the following is true
- (BOOL)userNotificationDelegatesImplementedAndActive {
  BOOL implementDelegate = [[UIApplication sharedApplication].delegate respondsToSelector:@selector(userNotificationCenter:didReceiveNotificationResponse:withCompletionHandler:)];
  BOOL isIOS10 = floor(NSFoundationVersionNumber) > NSFoundationVersionNumber_iOS_9_x_Max;
  return implementDelegate && isIOS10;
}
```

If you remove `launchOptions[UIApplicationLaunchOptionsRemoteNotificationKey]`, can you still repro?

**Comment by Bucimis** [comment] 2019-02-01 20:13
@nfrydenholm Great catch! Yep, the check is from the SDK. Thanks for the suggested code revision - that's indeed an improvement over how we do things today. We'll implement the fix and release it in a future version of the SDK.

Until the fix is available, would you be able to structure your code to work with the current implementation?

**Comment by nfrydenholm** [comment] 2019-02-04 10:19
Yes, we'll make sure not to pass in the UIApplicationLaunchOptionsRemoteNotificationKey to the Braze SDK until we get an updated version with the fix :)
I'm glad we were able to track down the problem 👍

**Comment by Bucimis** [comment] 2019-02-04 15:51
@nfrydenholm likewise! thanks for all your help and we'll let you know when the update is released 👍

**Comment by Bucimis** [comment] 2019-02-05 16:07
@nfrydenholm closing for now, we'll ping when the release is out

**Comment by Bucimis** [comment] 2019-02-26 00:56
@nfrydenholm Sorry to bring this back from the dead, but we had a few more questions on our end. From a cold start, in `didFinishLaunching`, our call to `userNotificationDelegatesImplementedAndActive` and subsequent `openUrl` processing is gated by `![application.delegate respondsToSelector:@selector(application:didReceiveRemoteNotification:fetchCompletionHandler:)]`. If the application delegate is implemented, we would expect the double `openUrl` issue to arise; however, in a UNUserNotificationCenter-only implementation, we'd expect only one call to `openUrl` from a cold start even if `userNotificationDelegatesImplementedAndActive` wasn't detecting the `UNUserNotificationCenter` delegate properly. 

As a result, our followup question is, does `[application.delegate respondsToSelector:@selector(application:didReceiveRemoteNotification:fetchCompletionHandler:)]` return `true` in your app, and if so, does removing your `application:didReceiveRemoteNotification:fetchCompletionHandler:` implementation fix the issue?

Thanks for bearing with us on this one!

**Comment by nfrydenholm** [comment] 2019-02-28 12:00
Sorry for the slow reply - I had overlooked the mail I got from Github.

I'll try to look into the didReceiveRemoteNotification, and post my findings here as soon as possible.

**Comment by nfrydenholm** [comment] 2019-02-28 14:03
We don't have that method implemented.
So adding these lines
``` 
    BOOL result = [application.delegate respondsToSelector:@selector(application:didReceiveRemoteNotification:fetchCompletionHandler:)];
    NSString *output = [NSString stringWithFormat:@"Responds to didReceiveRemoteNotification= %@", result ? @"YES" : @"NO"];
    LogDebug(output);
``` 
Gives this result
`DEBUG] Responds to didReceiveRemoteNotification= NO`

**Comment by Bucimis** [comment] 2019-02-28 22:30
@nfrydenholm, thanks for the response. That makes sense and potentially explains the double opens. The `application:didReceiveRemoteNotification:fetchCompletionHandler:` method actually needs to be implemented even when using `UNUserNotificationCenter` per https://www.braze.com/docs/developer_guide/platform_integration_guides/ios/push_notifications/integration/#step-5-enable-push-handling. If it's not present but other `UNUserNotificationCenter` methods are implemented, the SDK will call `openURL` twice.

Could you try implementing `application:didReceiveRemoteNotification:fetchCompletionHandler:` and see if that resolves the issue?

**Comment by nfrydenholm** [comment] 2019-03-01 16:02
Implementing the `
application:didReceiveRemoteNotification:fetchCompletionHandler:` seems to do the trick 👍

**Comment by Bucimis** [comment] 2019-03-01 16:58
@nfrydenholm great! excited to hear that it worked & thanks for your patience while going back and forth with us :)

**Closed by Bucimis** 2019-03-01 16:58 UTC
