### ISSUE TITLE
ABKAttributionData does not link/compile when I use_frameworks! in pod file

### ISSUE THREAD

**Issue by klivin** [Appboy/appboy-ios-sdk#80] opened 2016-09-01 07:08 UTC
I have messed with a number of project settings, yet I am still getting this linking error:

Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_ABKAttributionData", referenced from:
      objc-class-ref in SMLAppDelegate.o
ld: symbol(s) not found for architecture x86_64

The only thing that works is if I take out use_frameworks! from my Podfile.  However, with that setting in pods file, the app breaks during linking.  Everything else seems to be working as expected.  Any ideas?

**Comment by Wenzhi** [comment] 2016-09-01 16:18
Hey @klivin,

I suspect this might be a linking issue. As you are using `user_frameworks!` in your podfile, did you put the following code in your podfile as well?
```
post_install do |installer|
 installer.pods_project.targets.each do |target|
   target.build_configurations.each do |config|
     if target.name == "Appboy-iOS-SDK"
       config.build_settings["OTHER_LDFLAGS"] = '$(inherited) "-ObjC"'
     end
   end
 end
end
```

You can also find more detail and sample profile here:https://www.appboy.com/documentation/iOS/#step-2-constructing-the-podfile. Please let me know if you already added it, or still have the issue after adding it.

Thanks,
Wenzhi

**Comment by klivin** [comment] 2016-09-01 22:10
That was it! Thanks a lot!

**Comment by Wenzhi** [comment] 2016-09-01 22:14
Hey @klivin,

Glad to hear the issue is solved! I'm going to close this issue. Please feel free to contact us with any other issues or questions.

Thanks,
Wenzhi

**Closed by Wenzhi** 2016-09-01 22:14 UTC
