### ISSUE TITLE
Newsfeed connection error on iOS9

### ISSUE THREAD

**Issue by TaPhuocHai** [Appboy/appboy-ios-sdk#33] opened 2015-09-30 01:43 UTC
On newsfeed view, I click on a newsfeed to see detail. In detail page, it's loading normal and after 3,4 second, it show connection error.
I run it on iOS9, iOS8 is working.

PS: I added NSAppTransportSecurity for support http on ios9

**Comment by Wenzhi** [comment] 2015-09-30 03:08
Hi @TaPhuocHai,

I tested it on my test app with ATS disabled but cannot reproduce it. Could you provide more information about:
* What is the link of the news feed card?
* Your plist with how you added `http` as an ATS exception?

Thanks,
Wenzhi

**Comment by TaPhuocHai** [comment] 2015-09-30 07:01
1. Link of the newsfeed card:
http://tiki.vn/huggies?utm_source=tikiapp_ios&utm_medium=newsfeed&utm_campaign=ci_nha-ban-le-hang-dau-huggies

2. I have add ATS exception, you can see attach image
![screenshot 2015-09-30 14 00 39](https://cloud.githubusercontent.com/assets/1428095/10186495/a9f924a0-677b-11e5-8d1e-43c370f539d5.png)

**Comment by Wenzhi** [comment] 2015-09-30 16:35
Hi @TaPhuocHai 

I created a news feed card with the link you provided, and tested on our test app, but still cannot reproduce it. Could you give me the full detail about how you set the `NSAppTransportSecurity` in your plist? The picture you gave doesn't have the detail about NSExceptionDomains. 

I'll try to apply your plist setup to the test app and try again.

**Comment by TaPhuocHai** [comment] 2015-10-01 00:51
You can download the plist file here : 
https://dl.dropboxusercontent.com/u/37668715/Info.plist

Here is video about this bug:
https://youtu.be/w9q1nwXfUrs

**Comment by Wenzhi** [comment] 2015-10-01 16:54
Hi @TaPhuocHai,

I applied your plist file and still cannot reproduce it. It's our first time to hear a bug like this. 

Do you mind giving us more information:
* What is the SDK version you are using?
* Can you send me the console logs when you reproduce the error?
* You news feed integration Code
* I also notice that the link you gave me looks slightly different from the one in your video. Could you check the link you gave me and confirm that I've been testing the right link? The view I see looks like this:
![image](https://cloud.githubusercontent.com/assets/996652/10227399/11fc6d04-683b-11e5-9ea9-45c7d7eec69a.png)

If you don't want to show your code here, you can send them to wenzhi@appboy.com. I'll update this issue when we find out more.

**Comment by Wenzhi** [comment] 2015-11-17 16:28
@TaPhuocHai, 

Do you still have the issue?

**Comment by Wenzhi** [comment] 2015-12-17 17:09
Close the issue.

**Closed by Wenzhi** 2015-12-17 17:09 UTC
