### ISSUE TITLE
UILabel is not key value coding-compliant for the key nuiClass

### ISSUE THREAD

**Issue by zacwest** [Appboy/appboy-ios-sdk#148] opened 2018-05-16 23:36 UTC
## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.3
 SDK Version             | 3.4.0
 Integration Method      | cocoapods
 Xcode Version           | 9.3.1
 Repro rate              | always
 
## What did you do?

Ran the application.

## What did you expect to happen?

Loading the xib does not crash the app.

## What happened instead?

Loading the xib crashes the app.

## Steps to reproduce

1. Run the app
2. Have a campaign do an in-app message
3. Crash

## …

In `ABKInAppMessageModalViewController.m`, when it loads the bundle:

```objc
  [[NSBundle bundleForClass:[ABKInAppMessageModalViewController class]] loadNibNamed:@"ABKInAppMessageModalViewController"
                                                                               owner:self
                                                                             options:nil];
```

I'm seeing the UILabels inside have a `nuiClass` selector set, which does not exist on UILabel. This throws an exception which looks like:

[<UILabel 0x7f82eaa4c8d0> setValue:forUndefinedKey:]: this class is not key value coding-compliant for the key nuiClass.

If I remove the `nuiClass` "User-Defined Runtime Attributes" everything seems to work fine. Is this some vestigial thing?

**Comment by chshapiro** [comment] 2018-05-23 13:17
Hey @zacwest ,

Unfortunately we cannot reproduce this issue. The `nuiClass` key is used for customizing the in-app messages with NUI.

Are you doing any customization for in-app messages?

Thanks,
Chava

**Comment by chshapiro** [comment] 2018-06-19 15:57
@zacwest, closing for now. Please reopen the issue if you have any further questions. Thanks!

**Closed by chshapiro** 2018-06-19 15:57 UTC
