### ISSUE TITLE
Entire app UI freezing sometimes on iOS 9 when viewing newsfeed

### ISSUE THREAD

**Issue by octover** [Appboy/appboy-ios-sdk#42] opened 2016-01-08 09:23 UTC
We have a white label app so same code, different content for different publishers and some of our mutual customers use Appboy. While it has been seen on multiple Appboy API keys, there is one customer in particular, Kandy Magazine, that seems to trigger the UI freezing more reliably (I'm guessing something in their newsfeed items). Sometimes it is after viewing a news feed item that goes to a web view, and coming back. Other times it is just bringing up the newsfeed which is a tab in the iPad app. I don't believe I have ever recreated this in a Simulator, just on the device.

When this happens the device console will fill with these messages when tapping on the screen:

`BKSendHIDEvent: IOHIDEventSystemConnectionDispatchEvent error:0xE00002E8 -- Unknown event dropped`

Which isn't very helpful in finding an answer other than that the main thread may be blocked. It could be something on our end, but I can't really think of anything since it can happen just when the `ABKFeedViewControllerGenericContext` is presented from a tab bar. I know for sure the problem has existed with versions 2.16.1 and 2.17.1 of the SDK.

**Comment by billmag** [comment] 2016-01-08 16:30
Hey octover-

Are there any apps in addition to Kandy that we can take a look at to try and find some patterns as we investigate this?

-Bill

**Comment by octover** [comment] 2016-01-11 13:44
The Mag+ Designd Reviewer, but it is much harder to recreate in our own app. I will see if there are any others that have seen it.

**Comment by briancaw** [comment] 2016-01-21 03:37
Hi again @octover,

Have you had any luck reproducing on other apps or gathering more data on this issue?

I also have a few more questions:

1) Have you seen this behavior emerge in an upgrade?  Or is this for an app that started with a version that has the issue?
2)  Are you able to do diagnostics on the app to see memory/cpu usage...etc. during freezes?
3)  Can you share any details regarding your News Feed/Feedback Integration?  e.g. if you diverged from the default documentation at all.

I've downloaded the app and can repro; we should have more information in the near future regarding this.

Thanks,
Brian

**Comment by octover** [comment] 2016-01-21 09:11
1) Mostly upgraded apps, but we are able to reproduce with fresh installs of the app on devices as well.
2) Yes, and I can inspect the view hierarchy via the debugger, everything is still running, but since touch input is getting to the app it is effectively frozen.
3) It's very vanilla, we have a system that builds up the menu based on if Appboy is enabled for the app or not, but other than that it is `[[ABKFeedViewControllerGenericContext alloc] init]`

**Comment by briancaw** [comment] 2016-01-21 17:31
Thanks for that update and info @octover.  One more question for this - do you have any crash reports that have more information?  i.e. it seems that in this scenario if you background/foreground the app it crashes, so maybe there's something that's getting up to your crash reporting that can point towards what's happening or give more info?

Thanks,
Brian

**Comment by octover** [comment] 2016-01-22 13:49
I can include more, but looking at it, it is just that the UI is frozen and iOS is able to detect that. The relevant parts are below, I had just opened the app, tapped onto the newsfeed part, UI froze, background and foreground the app and it crashed.

```Exception Type:  00000020
Exception Codes: 0x000000008badf00d
Exception Note:  SIMULATED (this is NOT a crash)
Highlighted by Thread:  0

Application Specific Information:
com.magplus.generictester failed to scene-update after 10.00s

Elapsed total CPU time (seconds): 3.430 (user 3.430, system 0.000), 23% CPU 
Elapsed application CPU time (seconds): 0.004, 0% CPU```

**Comment by Wenzhi** [comment] 2016-02-11 17:21
Hi @octover,

Apologies for the delay. Could you give me more information about how you integrate Appboy's News Feed to the tabViewController, so I can recreate it in a sample app? Just based on the given messages it's not very clear what cause it. 

Thanks,
Wenzhi

**Comment by octover** [comment] 2016-02-16 07:58
Sorry for the delay, we just have a UITabBar and setting up `ABKFeedViewControllerGenericContext` as one of the view controllers. There is a wrapper view controller we are using to help with some UI layout stuff, but the problem persists if we remove that intermediary layer.

**Comment by Wenzhi** [comment] 2016-02-17 05:47
Hi @octover,

I tried to create a tab view controller and put an `ABKFeedViewControllerGenericContext` with Kandy's news feed, but I cannot reproduce the issue even with my best effort. I didn't see any tab view controller displayed in Kandy's iPhone app, however; I also noticed that most Kandy's news feed card have custom URL links. 

My guess is there might be something relate to how the tab view controller is set up with the news feed. Do you mind sending me a sample app with your tab view controller setups and custom URL handling, so I can pull in Kandy's news feed on your sample app and go from there?

Thanks,
Wenzhi

**Comment by carole-lavillonniere** [comment] 2016-02-24 15:11
We have the same kind of freezing, wth such a message appearing in the logs when touching the screen:

```
backboardd[60] <Warning>: BKSendHIDEvent: IOHIDEventSystemConnectionDispatchEvent error:0xE00002E8 -- Unknown event dropped
```
It happens when opening the app from a iOS9 universal link.
We are using the version 1.0.0 of the SDK:

```
pod 'Segment-Appboy',          '1.0.0'
```

**Comment by Wenzhi** [comment] 2016-02-24 15:45
Hi @carole-lavillonniere,

Does the universal link open a news feed, or call any Appboy function? Could you give us a universal link and more implementation detail relate to Appboy for us to repo?

Thanks,
Wenzhi

**Comment by briancaw** [comment] 2016-02-24 17:43
Hi @carole-lavillonniere @octover 

We'd like to follow up on this via email to iterate faster - do you have emails we can contact you at?

Thanks,
Brian

**Comment by carole-lavillonniere** [comment] 2016-02-24 18:12
Sure: cal@idagio.com

@Wenzhi I don't know what you mean with "News feed".

No Appboy function is directly called.

Any link to our web app, ie https://www.idagio.com/composers when open with the iOS app would potentially freeze it. It's not super easy to reproduce, it doesn't not always freeze.

**Comment by octover** [comment] 2016-02-25 09:55
It is now moot on our end. Our companies have ended their partnership and so we are removing Appboy from our platform. Our development cycle is such that we are going to do one last release next week with 2.18.4 in it and then remove Appboy.

**Comment by billmag** [comment] 2016-02-25 16:15
@octover -- thanks you for the update. We've enjoyed working with Mag+ over the years and wish you all the best of luck with your publishing platform. I'm going to close this issue as we were unable to replicate it with any other clients outside of the Mag+ integration.

We've followed up with @carole-lavillonniere to work through what sounds is a separate issue.

If anyone sees similar behavior in the future, please let us know on this thread, or email mobile [at] appboy.com.

**Closed by billmag** 2016-02-25 16:15 UTC
