### ISSUE TITLE
'ABKNavigationFeedbackViewController.h' file not found

### ISSUE THREAD

**Issue by MatijaKruljac** [Appboy/appboy-ios-sdk#121] opened 2017-09-25 09:18 UTC
* [ ] I have checked [Appboy's documentation](https://www.appboy.com/documentation/iOS/) and am still experiencing the issue.

# Report

## Describe your environment.

 Info                    | Value                               |
-------------------------|-------------------------------------|
 Platform Name           | ios
 Platform Version        | 11.0
 SDK Versions             | master, 3.1.0
 Integration Method      | cocoapods
 Xcode Version           | Xcode 9
 Repro rate              | all the time (100%)
 
## What did you do?
I downloaded appboy-ios-sdk from master and from 3.1.0 tag version. I have installed cocoapods, opened example .workspace in `Example` directory and then I tried to build and run project on simulator but I'm constantly getting following error message `appboy-ios-sdk-3.1.0/Example/Stopwatch/FeedAndFeedbackUIViewController.m:3:9: 'ABKNavigationFeedbackViewController.h' file not found`
![screen shot 2017-09-25 at 11 14 49 am](https://user-images.githubusercontent.com/21220713/30801222-dca0720c-a1e2-11e7-8397-b5e127a3e50d.png)

**Comment by MatijaKruljac** [comment] 2017-09-25 13:46
I fixed it. I added `use_frameworks!` in `podfile`.

**Comment by Wenzhi** [comment] 2017-09-25 14:05
Hey @MatijaKruljac,

Can I ask you:
- What's the Podfile in your Stopwatch? Did you use the `UI` or `Feedback` subspec?
- Can you see the `ABKNavigationFeedbackViewController.h` and `ABKNavigationFeedbakViewController.m` in your Pods project as following?
![image](https://user-images.githubusercontent.com/996652/30812539-03c82e06-a1d9-11e7-8aec-b7baaa9e0455.png)

Thanks,
Wenzhi

**Comment by MatijaKruljac** [comment] 2017-09-25 14:47
Hey @Wenzhi,

this is `podfile`:
```
source 'https://github.com/CocoaPods/Specs.git'

target :Stopwatch do
  platform :ios, '8.0'
  pod 'Appboy-iOS-SDK'
  pod 'NUI',:git => 'https://github.com/tombenner/nui.git'
  pod 'KKColorListPicker', :git => 'https://github.com/leoru/KKColorListPicker.git'
  pod 'Firebase/DynamicLinks'
  pod 'Branch'
  pod 'BuddyBuildSDK'
end

target :tvOS_Stopwatch do
  platform :tvos, '9.0'
  pod 'Appboy-tvOS-SDK'
end

target :tvOS_TVML_Stopwatch do
  platform :tvos, '9.0'
  pod 'Appboy-tvOS-SDK'
end

```

I think I used `UI`. And I can not see `ABKNavigationFeedbackViewController.h` and `ABKNavigationFeedbakViewController.m` files in my Pods.

Thanks,
MatijaKruljac

**Comment by Wenzhi** [comment] 2017-09-25 15:08
Hey @MatijaKruljac,

It seems that the Cocoapods didn't fetch the latest version of the SDK or didn't fetch all the files.  Could you check:
- What's the Cocoapods version you are using?
- What's the SDK version in the `Appboy.h` in your pods?

I also wonder if the issue is due to that Cocoapods caches old version of the SDK. In that case, could you try `pod cache clean --all` and then run `pod update` again?

Thanks,
Wenzhi

**Comment by MatijaKruljac** [comment] 2017-09-25 20:20
I'm using the latest Cocoapods version. I assume that SDK version is the latest version. When I downloaded the project from `master` branch I didn't change anything. I left it as it is. 

Also, I tried `pod cache clean --all` and then I ran `pod update`. Still getting the same result.

MatijaKruljac

**Comment by Wenzhi** [comment] 2017-09-25 20:29
Thanks for the info @MatijaKruljac. 

Can I ask you one more thing: could you share the `Podfile.lock` file in the `Example` folder? You should have one if you run `pod install` or `pod update` in `Example`.

Thanks,
Wenzhi

**Comment by MatijaKruljac** [comment] 2017-09-27 12:30
No problem @Wenzhi. 

Sorry for late response but I had some other work to do. 
In attachment is `Podfile.lock` file from `Example` directory.

[Podfile.lock.zip](https://github.com/Appboy/appboy-ios-sdk/files/1337074/Podfile.lock.zip)

Thanks for your help,
MatijaKruljac

**Comment by Wenzhi** [comment] 2017-09-27 15:57
Hi, @MatijaKruljac,

Thank you! From your Podfile.lock, it seems your Cocoapods is using Appboy SDK 2.30.0, and the Feedback view controllers were released in version 2.31.0. I wonder if there is an issue in the Cocoapods gem on your computer.

Could you follow https://guides.cocoapods.org/using/troubleshooting.html and see if that uninstall/re-install Cocoapods fixes the issue and let you pull the latest version of the SDK?

Thanks,
Wenzhi

**Comment by Wenzhi** [comment] 2017-10-09 15:49
Hey @MatijaKruljac,  

Did you try the suggestion above? Are you still seeing the issue?

Thanks,
Wenzhi

**Comment by Wenzhi** [comment] 2017-10-18 16:15
Hey @MatijaKruljac, 

I'm going to close this issue due to the inactivity. Please feel free to re-open it if you are still seeing the issue.

Thanks,
Wenzhi

**Closed by Wenzhi** 2017-10-18 16:15 UTC
